# Site settings
title: Anima
#email: anima-users@inria.fr

base-url: "/"
ref-url: "https://anima.irisa.fr"

description: library and python scripts for medical image processing

# Build settings
markdown: kramdown
