ANIMA: animaDWISimulatorFromDTI.cxx File Reference
animaDWISimulatorFromDTI.cxx File Reference
#include <animaDWISimulatorFromDTIImageFilter.h>
#include <fstream>
#include <itkImageFileReader.h>
#include <itkImageFileWriter.h>
#include <itkTimeProbe.h>
#include <tclap/CmdLine.h>
Functions
void loadBValues (std::vector< std::vector< float > > &directions, std::string &bvalsArg, std::vector< float > &mb)
void loadGradients (std::string &gradsArg, std::vector< std::vector< float > > &directions)
int main (int argc, char **argv)
Function Documentation
loadBValues()
void loadBValues (std::vector< std::vector< float > > & directions, std::string & bvalsArg, std::vector< float > & mb)
Definition at line 47 of file animaDWISimulatorFromDTI.cxx.
Referenced by main().
loadGradients()
void loadGradients (std::string & gradsArg, std::vector< std::vector< float > > & directions)
Definition at line 10 of file animaDWISimulatorFromDTI.cxx.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 78 of file animaDWISimulatorFromDTI.cxx.
References loadBValues(), and loadGradients().