ANIMA: animaNoiseGenerator.cxx File Reference
animaNoiseGenerator.cxx File Reference
#include <tclap/CmdLine.h>
#include <animaNoiseGeneratorImageFilter.h>
#include <animaReadWriteFunctions.h>
#include <animaRetrieveImageTypeMacros.h>
#include <animaKummerFunctions.h>
Classes
struct arguments
Functions
template<class ComponentType , unsigned int InputDim>
void addNoise (itk::ImageIOBase::Pointer imageIO, const arguments &args)
int main (int argc, char **argv)
template<class ComponentType >
void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments &args)
Function Documentation
addNoise()
template<class ComponentType , unsigned int InputDim> void addNoise (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 17 of file animaNoiseGenerator.cxx.
References arguments::gaussianNoise, arguments::input, arguments::nreplicates, arguments::nthreads, arguments::output, and arguments::sigma.
Referenced by retrieveNbDimensions().
main()
int main (int argc, char ** argv)
Definition at line 63 of file animaNoiseGenerator.cxx.
References ANIMA_RETRIEVE_COMPONENT_TYPE, arguments::gaussianNoise, anima::GetKummerFunctionValue(), arguments::imageIO, arguments::input, arguments::nreplicates, arguments::nthreads, arguments::output, retrieveNbDimensions(), and arguments::sigma.
retrieveNbDimensions()
template<class ComponentType > void retrieveNbDimensions (itk::ImageIOBase::Pointer imageIO, const arguments & args)
Definition at line 58 of file animaNoiseGenerator.cxx.
References addNoise(), and ANIMA_RETRIEVE_NUMBER_OF_DIMENSIONS.
Referenced by main().