ANIMA: animaMCMScalarMaps.cxx File Reference
animaMCMScalarMaps.cxx File Reference
#include <animaMCMFileReader.h>
#include <animaReadWriteFunctions.h>
#include <animaMCMScalarMapsImageFilter.h>
#include <itkTimeProbe.h>
#include <tclap/CmdLine.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 8 of file animaMCMScalarMaps.cxx.
References anima::MCMFileReader< PixelType, ImageDimension >::GetModelVectorImage(), anima::MCMFileReader< PixelType, ImageDimension >::SetFileName(), and anima::MCMFileReader< PixelType, ImageDimension >::Update().