ANIMA: animaMCMAverageImages.cxx File Reference
animaMCMAverageImages.cxx File Reference
#include <tclap/CmdLine.h>
#include <itkVectorImage.h>
#include <animaMCMAverageImagesImageFilter.h>
#include <animaMCMFileReader.h>
#include <animaMCMFileWriter.h>
#include <animaMultiCompartmentModelCreator.h>
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 10 of file animaMCMAverageImages.cxx.
References anima::MCMAverageImagesImageFilter< TPixelType >::AddMaskImage(), anima::FreeWater, anima::MultiCompartmentModelCreator::GetNewMultiCompartmentModel(), anima::IsotropicRestrictedWater, anima::MultiCompartmentModelCreator::SetCompartmentType(), anima::MultiCompartmentModelCreator::SetModelWithFreeWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithRestrictedWaterComponent(), anima::MultiCompartmentModelCreator::SetModelWithStaniszComponent(), anima::MultiCompartmentModelCreator::SetModelWithStationaryWaterComponent(), anima::MultiCompartmentModelCreator::SetNumberOfCompartments(), anima::MCMAverageImagesImageFilter< TPixelType >::SetReferenceOutputModel(), anima::Stanisz, and anima::StationaryWater.