ANIMA: anima::DirectionTransform< TScalarType > Class Template Reference
anima::DirectionTransform< TScalarType > Class Template Reference
#include <animaDirectionScaleSkewTransform.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::MatrixType MatrixType
typedef Superclass::OffsetType OffsetType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef DirectionTransform Self
typedef anima::DirectionScaleSkewTransform< TScalarType > Superclass
Public Types inherited from anima::DirectionScaleSkewTransform< TScalarType >
typedef Superclass::CenterType CenterType
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Matrix< ScalarType, 4, 4 > HomogeneousMatrixType
typedef Superclass::InputCovariantVectorType InputCovariantVectorType
typedef Superclass::InputPointType InputPointType
typedef Superclass::InputVectorType InputVectorType
typedef Superclass::InputVnlVectorType InputVnlVectorType
typedef Superclass::InverseMatrixType InverseMatrixType
typedef Superclass::JacobianType JacobianType
typedef Superclass::MatrixType MatrixType
typedef Superclass::OffsetType OffsetType
typedef Superclass::OutputCovariantVectorType OutputCovariantVectorType
typedef Superclass::OutputPointType OutputPointType
typedef Superclass::OutputVectorType OutputVectorType
typedef Superclass::OutputVnlVectorType OutputVnlVectorType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::ScalarType ScalarType
typedef DirectionScaleSkewTransform Self
typedef itk::MatrixOffsetTransformBase< TScalarType, 3 > Superclass
typedef Superclass::TranslationType TranslationType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual const ParametersType & GetParameters () const override
virtual void SetParameters (const ParametersType &parameters) override
Public Member Functions inherited from anima::DirectionScaleSkewTransform< TScalarType >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const ScalarType & GetLogFirstSkew () const
virtual const ScalarType & GetLogScale () const
virtual const ScalarType & GetLogSecondSkew () const
virtual const vnl_matrix< TScalarType > & GetLogTransform () const
virtual const itk::Vector< TScalarType, 12 > & GetLogVector () const
virtual const unsigned int & GetUniqueDirection () const
virtual const ScalarType & GetUniqueTranslation () const
virtual void SetGeometry (HomogeneousMatrixType &matrix, bool update=true)
virtual void SetIdentity () override
void SetLogFirstSkew (ScalarType skew, bool update=true)
void SetLogScale (ScalarType scale, bool update=true)
void SetLogSecondSkew (ScalarType skew, bool update=true)
void SetUniqueDirection (unsigned int direction)
void SetUniqueTranslation (ScalarType translation, bool update=true)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::DirectionScaleSkewTransform< TScalarType >
static Pointer New ()
Static Public Attributes
static const unsigned int ParametersDimension = 1
Static Public Attributes inherited from anima::DirectionScaleSkewTransform< TScalarType >
static const unsigned int InputSpaceDimension = 3
static const unsigned int OutputSpaceDimension = 3
static const unsigned int ParametersDimension = 4
static const unsigned int SpaceDimension = 3
Protected Member Functions
DirectionTransform ()
virtual void GetInternalExponential () override
virtual void GetInternalLogarithm () override
virtual void InternalApplyGeometry (MatrixType &linearMatrix, OffsetType &offset) override
Protected Member Functions inherited from anima::DirectionScaleSkewTransform< TScalarType >
virtual void ComputeMatrix () override
DirectionScaleSkewTransform ()
DirectionScaleSkewTransform (unsigned int ParamersDim)
void PrintSelf (std::ostream &os, itk::Indent indent) const override
~DirectionScaleSkewTransform ()
Additional Inherited Members
Protected Attributes inherited from anima::DirectionScaleSkewTransform< TScalarType >
vnl_matrix< TScalarType > m_ExpTransform
HomogeneousMatrixType m_Geometry
HomogeneousMatrixType m_GeometryInv
vnl_matrix< TScalarType > m_LogTransform
Detailed Description
template<class TScalarType = double>
class anima::DirectionTransform< TScalarType >
Definition at line 173 of file animaDirectionScaleSkewTransform.h.
Member Typedef Documentation
ConstPointer
template<class TScalarType = double> typedef itk::SmartPointer<const Self> anima::DirectionTransform< TScalarType >::ConstPointer
Definition at line 181 of file animaDirectionScaleSkewTransform.h.
MatrixType
template<class TScalarType = double> typedef Superclass::MatrixType anima::DirectionTransform< TScalarType >::MatrixType
Definition at line 184 of file animaDirectionScaleSkewTransform.h.
OffsetType
template<class TScalarType = double> typedef Superclass::OffsetType anima::DirectionTransform< TScalarType >::OffsetType
Definition at line 185 of file animaDirectionScaleSkewTransform.h.
ParametersType
template<class TScalarType = double> typedef Superclass::ParametersType anima::DirectionTransform< TScalarType >::ParametersType
Definition at line 183 of file animaDirectionScaleSkewTransform.h.
Pointer
template<class TScalarType = double> typedef itk::SmartPointer<Self> anima::DirectionTransform< TScalarType >::Pointer
Definition at line 180 of file animaDirectionScaleSkewTransform.h.
Self
template<class TScalarType = double> typedef DirectionTransform anima::DirectionTransform< TScalarType >::Self
Standard class typedefs.
Definition at line 178 of file animaDirectionScaleSkewTransform.h.
Superclass
template<class TScalarType = double> typedef anima::DirectionScaleSkewTransform<TScalarType> anima::DirectionTransform< TScalarType >::Superclass
Definition at line 179 of file animaDirectionScaleSkewTransform.h.
Constructor & Destructor Documentation
DirectionTransform()
template<class TScalarType = double> anima::DirectionTransform< TScalarType >::DirectionTransform () inline protected
Definition at line 200 of file animaDirectionScaleSkewTransform.h.
References anima::DirectionScaleSkewTransform< TScalarType >::GetInternalExponential(), anima::DirectionScaleSkewTransform< TScalarType >::GetInternalLogarithm(), and anima::DirectionScaleSkewTransform< TScalarType >::InternalApplyGeometry().
Member Function Documentation
CreateAnother()
template<class TScalarType = double> virtual::itk::LightObject::Pointer anima::DirectionTransform< TScalarType >::CreateAnother (void) const
GetInternalExponential()
template<class TScalarType > void anima::DirectionTransform< TScalarType >::GetInternalExponential () override protected virtual
Reimplemented from anima::DirectionScaleSkewTransform< TScalarType >.
Definition at line 468 of file animaDirectionScaleSkewTransform.hxx.
Referenced by anima::DirectionTransform< TScalarType >::GetInternalLogarithm().
GetInternalLogarithm()
template<class TScalarType > void anima::DirectionTransform< TScalarType >::GetInternalLogarithm () override protected virtual
Reimplemented from anima::DirectionScaleSkewTransform< TScalarType >.
Definition at line 459 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionTransform< TScalarType >::GetInternalExponential().
Referenced by anima::DirectionTransform< TScalarType >::InternalApplyGeometry().
GetNameOfClass()
template<class TScalarType = double> virtual const char* anima::DirectionTransform< TScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::DirectionScaleSkewTransform< TScalarType >.
GetParameters()
template<class TScalarType > const DirectionTransform< TScalarType >::ParametersType & anima::DirectionTransform< TScalarType >::GetParameters (void) const override virtual
Reimplemented from anima::DirectionScaleSkewTransform< TScalarType >.
Definition at line 423 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionTransform< TScalarType >::InternalApplyGeometry().
Referenced by anima::DirectionTransform< TScalarType >::SetParameters().
InternalApplyGeometry()
template<class TScalarType > void anima::DirectionTransform< TScalarType >::InternalApplyGeometry (MatrixType & linearMatrix, OffsetType & offset) override protected virtual
Reimplemented from anima::DirectionScaleSkewTransform< TScalarType >.
Definition at line 432 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionTransform< TScalarType >::GetInternalLogarithm().
Referenced by anima::DirectionTransform< TScalarType >::GetParameters().
New()
template<class TScalarType = double> static Pointer anima::DirectionTransform< TScalarType >::New () static
New macro for creation of through a Smart Pointer.
SetParameters()
template<class TScalarType > void anima::DirectionTransform< TScalarType >::SetParameters (const ParametersType & parameters) override virtual
Reimplemented from anima::DirectionScaleSkewTransform< TScalarType >.
Definition at line 408 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionTransform< TScalarType >::GetParameters().
Referenced by anima::DirectionScaleTransform< TScalarType >::GetInternalExponential().
Member Data Documentation
ParametersDimension
template<class TScalarType = double> const unsigned int anima::DirectionTransform< TScalarType >::ParametersDimension = 1 static
Dimension of the space.
Definition at line 194 of file animaDirectionScaleSkewTransform.h.
The documentation for this class was generated from the following files:
animaDirectionScaleSkewTransform.h
animaDirectionScaleSkewTransform.hxx