ANIMA: anima::BLMLambdaCostFunction Class Reference
anima::BLMLambdaCostFunction Class Reference
Levenberg-Marquardt lambda update cost function (phi) used for bounded levenberg marquardt optimizer .
#include <animaBLMLambdaCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef BLMLambdaCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
virtual unsigned int GetNumberOfParameters () const ITK_OVERRIDE
virtual bool GetSolutionInBounds ()
ParametersType & GetSolutionVector ()
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetDeltaParameter (double _arg)
void SetDValues (ParametersType &dVal)
void SetInputWorkMatricesAndVectorsFromQRDerivative (vnl_matrix< double > &qrDerivative, ParametersType &qtResiduals, unsigned int rank)
void SetInversePivotVector (std::vector< unsigned int > &invPiv)
virtual void SetJRank (unsigned int _arg)
void SetLowerBoundsPermutted (ParametersType &lb)
void SetPivotVector (std::vector< unsigned int > &piv)
void SetPreviousParametersPermutted (ParametersType &val)
void SetUpperBoundsPermutted (ParametersType &ub)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
BLMLambdaCostFunction ()
bool CheckSolutionIsInBounds (ParametersType &solutionVector) const
virtual ~BLMLambdaCostFunction () ITK_OVERRIDE
Detailed Description
Levenberg-Marquardt lambda update cost function (phi) used for bounded levenberg marquardt optimizer .
Definition at line 16 of file animaBLMLambdaCostFunction.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::BLMLambdaCostFunction::ConstPointer
Definition at line 24 of file animaBLMLambdaCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::BLMLambdaCostFunction::DerivativeType
Definition at line 33 of file animaBLMLambdaCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::BLMLambdaCostFunction::MeasureType
Definition at line 32 of file animaBLMLambdaCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::BLMLambdaCostFunction::ParametersType
Definition at line 34 of file animaBLMLambdaCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::BLMLambdaCostFunction::Pointer
Definition at line 23 of file animaBLMLambdaCostFunction.h.
Self
typedef BLMLambdaCostFunction anima::BLMLambdaCostFunction::Self
Standard class typedefs.
Definition at line 21 of file animaBLMLambdaCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::BLMLambdaCostFunction::Superclass
Definition at line 22 of file animaBLMLambdaCostFunction.h.
Constructor & Destructor Documentation
BLMLambdaCostFunction()
anima::BLMLambdaCostFunction::BLMLambdaCostFunction () inline protected
Definition at line 58 of file animaBLMLambdaCostFunction.h.
~BLMLambdaCostFunction()
virtual anima::BLMLambdaCostFunction::~BLMLambdaCostFunction () inline protected virtual
Definition at line 62 of file animaBLMLambdaCostFunction.h.
Member Function Documentation
CheckSolutionIsInBounds()
bool anima::BLMLambdaCostFunction::CheckSolutionIsInBounds (ParametersType & solutionVector) const protected
Definition at line 88 of file animaBLMLambdaCostFunction.cxx.
Referenced by GetValue().
CreateAnother()
virtual::itk::LightObject::Pointer anima::BLMLambdaCostFunction::CreateAnother (void) const
GetDerivative()
void anima::BLMLambdaCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 105 of file animaBLMLambdaCostFunction.cxx.
References anima::LowerTriangularSolver().
GetNameOfClass()
virtual const char* anima::BLMLambdaCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
virtual unsigned int anima::BLMLambdaCostFunction::GetNumberOfParameters () const inline virtual
Definition at line 39 of file animaBLMLambdaCostFunction.h.
GetSolutionInBounds()
virtual bool anima::BLMLambdaCostFunction::GetSolutionInBounds () virtual
GetSolutionVector()
ParametersType& anima::BLMLambdaCostFunction::GetSolutionVector () inline
Definition at line 55 of file animaBLMLambdaCostFunction.h.
GetValue()
BLMLambdaCostFunction::MeasureType anima::BLMLambdaCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 9 of file animaBLMLambdaCostFunction.cxx.
References CheckSolutionIsInBounds(), anima::QRGivensDecomposition(), and anima::UpperTriangularSolver().
New()
static Pointer anima::BLMLambdaCostFunction::New () static
Method for creation through the object factory.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::BoundedLevenbergMarquardtOptimizer().
SetDeltaParameter()
virtual void anima::BLMLambdaCostFunction::SetDeltaParameter (double _arg) virtual
SetDValues()
void anima::BLMLambdaCostFunction::SetDValues (ParametersType & dVal) inline
Definition at line 45 of file animaBLMLambdaCostFunction.h.
SetInputWorkMatricesAndVectorsFromQRDerivative()
void anima::BLMLambdaCostFunction::SetInputWorkMatricesAndVectorsFromQRDerivative (vnl_matrix< double > & qrDerivative, ParametersType & qtResiduals, unsigned int rank)
Definition at line 144 of file animaBLMLambdaCostFunction.cxx.
SetInversePivotVector()
void anima::BLMLambdaCostFunction::SetInversePivotVector (std::vector< unsigned int > & invPiv) inline
Definition at line 46 of file animaBLMLambdaCostFunction.h.
SetJRank()
virtual void anima::BLMLambdaCostFunction::SetJRank (unsigned int _arg) virtual
SetLowerBoundsPermutted()
void anima::BLMLambdaCostFunction::SetLowerBoundsPermutted (ParametersType & lb) inline
Definition at line 48 of file animaBLMLambdaCostFunction.h.
SetPivotVector()
void anima::BLMLambdaCostFunction::SetPivotVector (std::vector< unsigned int > & piv) inline
Definition at line 47 of file animaBLMLambdaCostFunction.h.
SetPreviousParametersPermutted()
void anima::BLMLambdaCostFunction::SetPreviousParametersPermutted (ParametersType & val) inline
Definition at line 50 of file animaBLMLambdaCostFunction.h.
SetUpperBoundsPermutted()
void anima::BLMLambdaCostFunction::SetUpperBoundsPermutted (ParametersType & ub) inline
Definition at line 49 of file animaBLMLambdaCostFunction.h.
The documentation for this class was generated from the following files:
animaBLMLambdaCostFunction.h
animaBLMLambdaCostFunction.cxx