ANIMA: anima::GaussLaguerreQuadrature Class Reference
anima::GaussLaguerreQuadrature Class Reference
Computes the Gauss Laguerre quadrature of a function defined from R^+ into R. Recenters the function on the interest zone with an affine relation, then uses Gauss Legendre on the left out part of the function and computes the main part with Gauss Laguerre.
#include <animaGaussLaguerreQuadrature.h>
Public Member Functions
GaussLaguerreQuadrature ()
template<class FunctionType >
double GetIntegralValue (FunctionType integrand)
void SetInterestZone (double minVal, double maxVal)
Specifies region on which the main part of the function is to be seen. If not specified, R^+ is the region.
virtual ~GaussLaguerreQuadrature ()
Detailed Description
Computes the Gauss Laguerre quadrature of a function defined from R^+ into R. Recenters the function on the interest zone with an affine relation, then uses Gauss Legendre on the left out part of the function and computes the main part with Gauss Laguerre.
Definition at line 15 of file animaGaussLaguerreQuadrature.h.
Constructor & Destructor Documentation
GaussLaguerreQuadrature()
anima::GaussLaguerreQuadrature::GaussLaguerreQuadrature ()
Definition at line 7 of file animaGaussLaguerreQuadrature.cxx.
~GaussLaguerreQuadrature()
virtual anima::GaussLaguerreQuadrature::~GaussLaguerreQuadrature () inline virtual
Definition at line 19 of file animaGaussLaguerreQuadrature.h.
Member Function Documentation
GetIntegralValue()
template<class FunctionType > double anima::GaussLaguerreQuadrature::GetIntegralValue (FunctionType integrand) inline
Definition at line 25 of file animaGaussLaguerreQuadrature.h.
Referenced by main(), anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative(), anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS(), and anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS().
SetInterestZone()
void anima::GaussLaguerreQuadrature::SetInterestZone (double minVal, double maxVal)
Specifies region on which the main part of the function is to be seen. If not specified, R^+ is the region.
Definition at line 13 of file animaGaussLaguerreQuadrature.cxx.
Referenced by main(), anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative(), anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS(), and anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS().
The documentation for this class was generated from the following files:
animaGaussLaguerreQuadrature.h
animaGaussLaguerreQuadrature.cxx