ANIMA: anima::LocalPatchMeanDistanceImageFilter< PixelScalarType > Class Template Reference
anima::LocalPatchMeanDistanceImageFilter< PixelScalarType > Class Template Reference
#include <animaLocalPatchMeanDistanceImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef vnl_matrix< double > CovarianceType
typedef InputImageType::IndexType InputImageIndexType
typedef InputImageType::Pointer InputImagePointer
typedef itk::VectorImage< PixelScalarType, 3 > InputImageType
typedef Superclass::MaskImageType MaskImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::Image< PixelScalarType, 3 > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef LocalPatchMeanDistanceImageFilter< PixelScalarType > Self
typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > Superclass
typedef InputImageType::PixelType VectorType
Public Types inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef MaskImageType::Pointer MaskImagePointer
typedef itk::Image< unsigned char, itk::VectorImage< PixelScalarType, 3 > ::ImageDimension > MaskImageType
typedef MaskImageType::IndexType MaskIndexType
typedef MaskImageType::RegionType MaskRegionType
typedef MaskImageType::SizeType MaskSizeType
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef MaskedImageToImageFilter Self
typedef anima::NumberedThreadImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< PixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Types inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef NumberedThreadImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > > Superclass
typedef itk::ImageSource< itk::Image< PixelScalarType, 3 > >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetPatchHalfSize (unsigned int _arg)
Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual MaskImageType * GetComputationMask ()
virtual void SetComputationMask (MaskImagePointer _arg)
Public Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual OutputImageRegionType GetComputationRegion ()
virtual void SetComputationRegion (OutputImageRegionType _arg)
virtual void SetNumberOfPointsToProcess (unsigned int _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static Pointer New ()
Static Public Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
void DynamicThreadedGenerateData (const OutputImageRegionType &outputRegionForThread) ITK_OVERRIDE
LocalPatchMeanDistanceImageFilter ()
virtual ~LocalPatchMeanDistanceImageFilter ()
Protected Member Functions inherited from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual void CheckComputationMask ()
void InitializeComputationRegionFromMask ()
MaskedImageToImageFilter ()
virtual ~MaskedImageToImageFilter ()
Protected Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
virtual void GenerateData () ITK_OVERRIDE
unsigned int GetSafeThreadId ()
void IncrementNumberOfProcessedPoints ()
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< PixelScalarType, 3 > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
NumberedThreadImageToImageFilter ()
void SafeReleaseThreadId (unsigned int threadId)
virtual void ThreadProcessSlices ()
virtual ~NumberedThreadImageToImageFilter ()
Additional Inherited Members
Static Public Attributes inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static constexpr unsigned int OutputImageDimension
Static Protected Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >
static ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<class PixelScalarType>
class anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >
Definition at line 14 of file animaLocalPatchMeanDistanceImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class PixelScalarType> typedef itk::SmartPointer<const Self> anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::ConstPointer
Definition at line 21 of file animaLocalPatchMeanDistanceImageFilter.h.
CovarianceType
template<class PixelScalarType> typedef vnl_matrix<double> anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::CovarianceType
Definition at line 35 of file animaLocalPatchMeanDistanceImageFilter.h.
InputImageIndexType
template<class PixelScalarType> typedef InputImageType::IndexType anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::InputImageIndexType
Definition at line 38 of file animaLocalPatchMeanDistanceImageFilter.h.
InputImagePointer
template<class PixelScalarType> typedef InputImageType::Pointer anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::InputImagePointer
Definition at line 37 of file animaLocalPatchMeanDistanceImageFilter.h.
InputImageType
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType, 3> anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::InputImageType
Image typedef support
Definition at line 30 of file animaLocalPatchMeanDistanceImageFilter.h.
MaskImageType
template<class PixelScalarType> typedef Superclass::MaskImageType anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::MaskImageType
Definition at line 43 of file animaLocalPatchMeanDistanceImageFilter.h.
OutputImagePointer
template<class PixelScalarType> typedef OutputImageType::Pointer anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 39 of file animaLocalPatchMeanDistanceImageFilter.h.
OutputImageRegionType
template<class PixelScalarType> typedef Superclass::OutputImageRegionType anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 44 of file animaLocalPatchMeanDistanceImageFilter.h.
OutputImageType
template<class PixelScalarType> typedef itk::Image<PixelScalarType, 3> anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::OutputImageType
Definition at line 31 of file animaLocalPatchMeanDistanceImageFilter.h.
Pointer
template<class PixelScalarType> typedef itk::SmartPointer<Self> anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::Pointer
Definition at line 20 of file animaLocalPatchMeanDistanceImageFilter.h.
Self
template<class PixelScalarType> typedef LocalPatchMeanDistanceImageFilter<PixelScalarType> anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 19 of file animaLocalPatchMeanDistanceImageFilter.h.
Superclass
template<class PixelScalarType> typedef anima::MaskedImageToImageFilter< InputImageType, OutputImageType > anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::Superclass
Superclass typedefs.
Definition at line 42 of file animaLocalPatchMeanDistanceImageFilter.h.
VectorType
template<class PixelScalarType> typedef InputImageType::PixelType anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::VectorType
Definition at line 33 of file animaLocalPatchMeanDistanceImageFilter.h.
Constructor & Destructor Documentation
LocalPatchMeanDistanceImageFilter()
template<class PixelScalarType> anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::LocalPatchMeanDistanceImageFilter () inline protected
Definition at line 49 of file animaLocalPatchMeanDistanceImageFilter.h.
~LocalPatchMeanDistanceImageFilter()
template<class PixelScalarType> virtual anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::~LocalPatchMeanDistanceImageFilter () inline protected virtual
Definition at line 59 of file animaLocalPatchMeanDistanceImageFilter.h.
References anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::DynamicThreadedGenerateData().
Member Function Documentation
BeforeThreadedGenerateData()
template<class PixelScalarType > void anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::BeforeThreadedGenerateData () protected virtual
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
Definition at line 15 of file animaLocalPatchMeanDistanceImageFilter.hxx.
References anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::DynamicThreadedGenerateData().
Referenced by anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::~LocalPatchMeanDistanceImageFilter().
CreateAnother()
template<class PixelScalarType> virtual::itk::LightObject::Pointer anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::CreateAnother (void) const
DynamicThreadedGenerateData()
template<class PixelScalarType > void anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::DynamicThreadedGenerateData (const OutputImageRegionType & outputRegionForThread) protected
Definition at line 29 of file animaLocalPatchMeanDistanceImageFilter.hxx.
References anima::computePatchMeanAndCovariance(), and anima::VectorMeansTest().
Referenced by anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::~LocalPatchMeanDistanceImageFilter().
GetNameOfClass()
template<class PixelScalarType> virtual const char* anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented from anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >.
New()
template<class PixelScalarType> static Pointer anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
Referenced by anima::LowMemoryLocalPatchMeanDistanceBridge::Update().
SetPatchHalfSize()
template<class PixelScalarType> virtual void anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >::SetPatchHalfSize (unsigned int _arg) virtual
The documentation for this class was generated from the following files:
animaLocalPatchMeanDistanceImageFilter.h
animaLocalPatchMeanDistanceImageFilter.hxx