ANIMA: anima::B1GammaMixtureT2RelaxometryCostFunction Class Reference
anima::B1GammaMixtureT2RelaxometryCostFunction Class Reference
#include <animaB1GammaMixtureT2RelaxometryCostFunction.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
using LECalculatorPointer = LECalculatorType::Pointer
using LECalculatorType = anima::LogEuclideanTensorCalculator< double >
typedef vnl_matrix< double > MatrixType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef B1GammaMixtureT2RelaxometryCostFunction Self
typedef SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
ParametersType & GetOptimalT2Weights ()
virtual double GetSigmaSquare ()
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetConstrainedParameters (bool _arg)
virtual void SetEchoSpacing (double _arg)
virtual void SetExcitationFlipAngle (double _arg)
virtual void SetGammaIntegralTolerance (double _arg)
void SetGammaMeans (std::vector< double > &val)
void SetGammaVariances (std::vector< double > &val)
virtual void SetT1Value (double _arg)
void SetT2RelaxometrySignals (ParametersType &relaxoSignals)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
B1GammaMixtureT2RelaxometryCostFunction ()
void PrepareDataForDerivative () const
void PrepareDataForLLS () const
void SolveLinearLeastSquares () const
Computes maximum likelihood estimates of weights.
virtual ~B1GammaMixtureT2RelaxometryCostFunction ()
Detailed Description
Definition at line 17 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
Member Typedef Documentation
ConstPointer
typedef itk::SmartPointer<const Self> anima::B1GammaMixtureT2RelaxometryCostFunction::ConstPointer
Definition at line 25 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::B1GammaMixtureT2RelaxometryCostFunction::DerivativeType
Definition at line 33 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
LECalculatorPointer
using anima::B1GammaMixtureT2RelaxometryCostFunction::LECalculatorPointer = LECalculatorType::Pointer
Definition at line 38 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
LECalculatorType
using anima::B1GammaMixtureT2RelaxometryCostFunction::LECalculatorType = anima::LogEuclideanTensorCalculator <double>
Definition at line 37 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
MatrixType
typedef vnl_matrix<double> anima::B1GammaMixtureT2RelaxometryCostFunction::MatrixType
Definition at line 34 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::B1GammaMixtureT2RelaxometryCostFunction::MeasureType
Definition at line 32 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::B1GammaMixtureT2RelaxometryCostFunction::ParametersType
Definition at line 35 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::B1GammaMixtureT2RelaxometryCostFunction::Pointer
Definition at line 24 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
Self
typedef B1GammaMixtureT2RelaxometryCostFunction anima::B1GammaMixtureT2RelaxometryCostFunction::Self
Standard class typedefs.
Definition at line 22 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
Superclass
typedef SingleValuedCostFunction anima::B1GammaMixtureT2RelaxometryCostFunction::Superclass
Definition at line 23 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
Constructor & Destructor Documentation
B1GammaMixtureT2RelaxometryCostFunction()
anima::B1GammaMixtureT2RelaxometryCostFunction::B1GammaMixtureT2RelaxometryCostFunction () inline protected
Definition at line 72 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
References anima::NNLSOptimizer::New().
~B1GammaMixtureT2RelaxometryCostFunction()
virtual anima::B1GammaMixtureT2RelaxometryCostFunction::~B1GammaMixtureT2RelaxometryCostFunction () inline protected virtual
Definition at line 81 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::B1GammaMixtureT2RelaxometryCostFunction::CreateAnother (void) const
GetDerivative()
void anima::B1GammaMixtureT2RelaxometryCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 160 of file animaB1GammaMixtureT2RelaxometryCostFunction.cxx.
References GetNumberOfParameters(), and PrepareDataForDerivative().
GetNameOfClass()
virtual const char* anima::B1GammaMixtureT2RelaxometryCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::B1GammaMixtureT2RelaxometryCostFunction::GetNumberOfParameters () const inline
Definition at line 60 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
Referenced by GetDerivative(), GetValue(), PrepareDataForDerivative(), and PrepareDataForLLS().
GetOptimalT2Weights()
ParametersType& anima::B1GammaMixtureT2RelaxometryCostFunction::GetOptimalT2Weights () inline
Definition at line 69 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
GetSigmaSquare()
virtual double anima::B1GammaMixtureT2RelaxometryCostFunction::GetSigmaSquare () virtual
GetValue()
B1GammaMixtureT2RelaxometryCostFunction::MeasureType anima::B1GammaMixtureT2RelaxometryCostFunction::GetValue (const ParametersType & parameters) const virtual
The measure type shall be used for computing the cost function value to observe convergence Parameters are set as {flip_angle,theta_1,theta_2,theta_3} for unconstrained estimation Or {flip_angle,theta_2} for constrained
Definition at line 12 of file animaB1GammaMixtureT2RelaxometryCostFunction.cxx.
References GetNumberOfParameters(), PrepareDataForLLS(), and SolveLinearLeastSquares().
New()
static Pointer anima::B1GammaMixtureT2RelaxometryCostFunction::New () static
PrepareDataForDerivative()
void anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative () const protected
Definition at line 259 of file animaB1GammaMixtureT2RelaxometryCostFunction.cxx.
References anima::GaussLaguerreQuadrature::GetIntegralValue(), GetNumberOfParameters(), anima::B1GammaDerivativeDistributionIntegrand::SetB1DerivativeFlag(), anima::B1GammaDistributionIntegrand::SetEchoNumber(), anima::B1GammaDistributionIntegrand::SetFlipAngle(), anima::B1GammaDistributionIntegrand::SetGammaMean(), anima::B1GammaDistributionIntegrand::SetGammaVariance(), anima::GaussLaguerreQuadrature::SetInterestZone(), and anima::B1GammaDistributionIntegrand::SetT1Value().
Referenced by GetDerivative().
PrepareDataForLLS()
void anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS () const protected
Definition at line 27 of file animaB1GammaMixtureT2RelaxometryCostFunction.cxx.
References anima::GaussLaguerreQuadrature::GetIntegralValue(), GetNumberOfParameters(), anima::CholeskyDecomposition::PerformDecomposition(), anima::B1GammaDistributionIntegrand::SetEchoNumber(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::B1GammaDistributionIntegrand::SetFlipAngle(), anima::B1GammaDistributionIntegrand::SetGammaMean(), anima::B1GammaDistributionIntegrand::SetGammaVariance(), anima::CholeskyDecomposition::SetInputMatrix(), anima::GaussLaguerreQuadrature::SetInterestZone(), anima::EPGSignalSimulator::SetNumberOfEchoes(), anima::B1GammaDistributionIntegrand::SetT1Value(), and anima::CholeskyDecomposition::SolveLinearSystem().
Referenced by GetValue().
SetConstrainedParameters()
virtual void anima::B1GammaMixtureT2RelaxometryCostFunction::SetConstrainedParameters (bool _arg) virtual
SetEchoSpacing()
virtual void anima::B1GammaMixtureT2RelaxometryCostFunction::SetEchoSpacing (double _arg) virtual
SetExcitationFlipAngle()
virtual void anima::B1GammaMixtureT2RelaxometryCostFunction::SetExcitationFlipAngle (double _arg) virtual
SetGammaIntegralTolerance()
virtual void anima::B1GammaMixtureT2RelaxometryCostFunction::SetGammaIntegralTolerance (double _arg) virtual
SetGammaMeans()
void anima::B1GammaMixtureT2RelaxometryCostFunction::SetGammaMeans (std::vector< double > & val) inline
Definition at line 54 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
SetGammaVariances()
void anima::B1GammaMixtureT2RelaxometryCostFunction::SetGammaVariances (std::vector< double > & val) inline
Definition at line 55 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
SetT1Value()
virtual void anima::B1GammaMixtureT2RelaxometryCostFunction::SetT1Value (double _arg) virtual
SetT2RelaxometrySignals()
void anima::B1GammaMixtureT2RelaxometryCostFunction::SetT2RelaxometrySignals (ParametersType & relaxoSignals) inline
Definition at line 51 of file animaB1GammaMixtureT2RelaxometryCostFunction.h.
SolveLinearLeastSquares()
void anima::B1GammaMixtureT2RelaxometryCostFunction::SolveLinearLeastSquares () const protected
Computes maximum likelihood estimates of weights.
Definition at line 140 of file animaB1GammaMixtureT2RelaxometryCostFunction.cxx.
Referenced by GetValue().
The documentation for this class was generated from the following files:
animaB1GammaMixtureT2RelaxometryCostFunction.h
animaB1GammaMixtureT2RelaxometryCostFunction.cxx