ANIMA: anima::LogEuclideanTensorCalculator< TScalarType > Class Template Reference
anima::LogEuclideanTensorCalculator< TScalarType > Class Template Reference
#include <animaBaseTensorTools.h>
Public Types
using ConstPointer = itk::SmartPointer< const Self >
using EigenAnalysisType = itk::SymmetricEigenAnalysis< vnl_matrix< double >, vnl_diag_matrix< double >, vnl_matrix< double > >
using Pointer = itk::SmartPointer< Self >
using Self = LogEuclideanTensorCalculator< TScalarType >
using Superclass = itk::LightObject
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
void GetTensorExponential (const vnl_matrix< TScalarType > &tensor, vnl_matrix< TScalarType > &log_tensor)
void GetTensorLogarithm (const vnl_matrix< TScalarType > &tensor, vnl_matrix< TScalarType > &log_tensor)
void GetTensorPower (const vnl_matrix< TScalarType > &tensor, vnl_matrix< TScalarType > &outputTensor, double powerValue)
Static Public Member Functions
static Pointer New ()
Detailed Description
template<class TScalarType>
class anima::LogEuclideanTensorCalculator< TScalarType >
Definition at line 18 of file animaBaseTensorTools.h.
Member Typedef Documentation
ConstPointer
template<class TScalarType> using anima::LogEuclideanTensorCalculator< TScalarType >::ConstPointer = itk::SmartPointer<const Self>
Definition at line 24 of file animaBaseTensorTools.h.
EigenAnalysisType
template<class TScalarType> using anima::LogEuclideanTensorCalculator< TScalarType >::EigenAnalysisType = itk::SymmetricEigenAnalysis < vnl_matrix <double>, vnl_diag_matrix<double>, vnl_matrix <double> >
Definition at line 31 of file animaBaseTensorTools.h.
Pointer
template<class TScalarType> using anima::LogEuclideanTensorCalculator< TScalarType >::Pointer = itk::SmartPointer<Self>
Definition at line 23 of file animaBaseTensorTools.h.
Self
template<class TScalarType> using anima::LogEuclideanTensorCalculator< TScalarType >::Self = LogEuclideanTensorCalculator <TScalarType>
Definition at line 21 of file animaBaseTensorTools.h.
Superclass
template<class TScalarType> using anima::LogEuclideanTensorCalculator< TScalarType >::Superclass = itk::LightObject
Definition at line 22 of file animaBaseTensorTools.h.
Member Function Documentation
CreateAnother()
template<class TScalarType> virtual::itk::LightObject::Pointer anima::LogEuclideanTensorCalculator< TScalarType >::CreateAnother (void) const
GetNameOfClass()
template<class TScalarType> virtual const char* anima::LogEuclideanTensorCalculator< TScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetTensorExponential()
template<class TScalarType > void anima::LogEuclideanTensorCalculator< TScalarType >::GetTensorExponential (const vnl_matrix< TScalarType > & tensor, vnl_matrix< TScalarType > & log_tensor)
Definition at line 64 of file animaBaseTensorTools.hxx.
References anima::RecomposeTensor().
Referenced by anima::dtiTractographyImageFilter::ComputeAdditionalScalarMaps().
GetTensorLogarithm()
template<class TScalarType > void anima::LogEuclideanTensorCalculator< TScalarType >::GetTensorLogarithm (const vnl_matrix< TScalarType > & tensor, vnl_matrix< TScalarType > & log_tensor)
Definition at line 14 of file animaBaseTensorTools.hxx.
References anima::RecomposeTensor().
GetTensorPower()
template<class TScalarType > void anima::LogEuclideanTensorCalculator< TScalarType >::GetTensorPower (const vnl_matrix< TScalarType > & tensor, vnl_matrix< TScalarType > & outputTensor, double powerValue)
Definition at line 39 of file animaBaseTensorTools.hxx.
References anima::RecomposeTensor().
New()
template<class TScalarType> static Pointer anima::LogEuclideanTensorCalculator< TScalarType >::New () static
Referenced by anima::MCMWeightedAverager::MCMWeightedAverager().
The documentation for this class was generated from the following files:
animaBaseTensorTools.h
animaBaseTensorTools.hxx