ANIMA: anima::B1GMMDistributionIntegrand Class Reference
anima::B1GMMDistributionIntegrand Class Reference
Integrand to compute the internal integral per distribution in B1GMMRelaxometryCostFunction.
#include <animaB1GMMDistributionIntegrand.h>
Public Types
using EPGVectorsMapType = std::map< double, anima::EPGSignalSimulator::RealVectorType >
Public Member Functions
B1GMMDistributionIntegrand (anima::EPGSignalSimulator &sigSim, EPGVectorsMapType &val)
virtual double operator() (double const t)
void SetEchoNumber (unsigned int val)
void SetFlipAngle (double val)
void SetGaussianMean (double val)
void SetGaussianVariance (double val)
void SetT1Value (double val)
Detailed Description
Integrand to compute the internal integral per distribution in B1GMMRelaxometryCostFunction.
Definition at line 14 of file animaB1GMMDistributionIntegrand.h.
Member Typedef Documentation
EPGVectorsMapType
using anima::B1GMMDistributionIntegrand::EPGVectorsMapType = std::map <double, anima::EPGSignalSimulator::RealVectorType>
Definition at line 17 of file animaB1GMMDistributionIntegrand.h.
Constructor & Destructor Documentation
B1GMMDistributionIntegrand()
anima::B1GMMDistributionIntegrand::B1GMMDistributionIntegrand (anima::EPGSignalSimulator & sigSim, EPGVectorsMapType & val) inline
Definition at line 18 of file animaB1GMMDistributionIntegrand.h.
Member Function Documentation
operator()()
double anima::B1GMMDistributionIntegrand::operator() (double const t) virtual
Definition at line 6 of file animaB1GMMDistributionIntegrand.cxx.
References anima::EPGSignalSimulator::GetValue().
SetEchoNumber()
void anima::B1GMMDistributionIntegrand::SetEchoNumber (unsigned int val) inline
Definition at line 23 of file animaB1GMMDistributionIntegrand.h.
Referenced by anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS().
SetFlipAngle()
void anima::B1GMMDistributionIntegrand::SetFlipAngle (double val) inline
Definition at line 22 of file animaB1GMMDistributionIntegrand.h.
Referenced by anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS().
SetGaussianMean()
void anima::B1GMMDistributionIntegrand::SetGaussianMean (double val) inline
Definition at line 25 of file animaB1GMMDistributionIntegrand.h.
Referenced by anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS().
SetGaussianVariance()
void anima::B1GMMDistributionIntegrand::SetGaussianVariance (double val) inline
Definition at line 26 of file animaB1GMMDistributionIntegrand.h.
Referenced by anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS().
SetT1Value()
void anima::B1GMMDistributionIntegrand::SetT1Value (double val) inline
Definition at line 21 of file animaB1GMMDistributionIntegrand.h.
Referenced by anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS().
The documentation for this class was generated from the following files:
animaB1GMMDistributionIntegrand.h
animaB1GMMDistributionIntegrand.cxx