ANIMA: anima::DTIScalarMapsImageFilter< ImageDimension > Class Template Reference
anima::DTIScalarMapsImageFilter< ImageDimension > Class Template Reference
Applies an variance filter to an image.
#include <animaDTIScalarMapsImageFilter.h>
Public Types
typedef OutputImageType ADCImageType
typedef itk::SmartPointer< const Self > ConstPointer
typedef OutputImageType FAImageType
typedef itk::VectorImage< double, ImageDimension > InputImageType
typedef OutputImageType::RegionType OutputImageRegionType
typedef itk::Image< double, ImageDimension > OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef DTIScalarMapsImageFilter Self
typedef anima::NumberedThreadImageToImageFilter< InputImageType, OutputImageType > Superclass
typedef TensorImageType::RegionType TensorImageRegionType
typedef TensorImageType::SizeType TensorImageSizeType
typedef InputImageType TensorImageType
typedef TensorImageType::PixelType TensorVectorType
Public Types inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > >
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef NumberedThreadImageToImageFilter Self
typedef itk::ImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > > Superclass
typedef itk::ImageSource< itk::Image< double, ImageDimension > >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
OutputImageType::Pointer GetADCImage ()
OutputImageType::Pointer GetAxialDiffusivityImage ()
OutputImageType::Pointer GetFAImage ()
virtual const char * GetNameOfClass () const
OutputImageType::Pointer GetRadialDiffusivityImage ()
itk::DataObject::Pointer MakeOutput (itk::ProcessObject::DataObjectPointerArraySizeType idx) ITK_OVERRIDE
Public Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > >
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual OutputImageRegionType GetComputationRegion ()
virtual void SetComputationRegion (OutputImageRegionType _arg)
virtual void SetNumberOfPointsToProcess (unsigned int _arg)
Static Public Member Functions
static Pointer New ()
Static Public Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > >
static Pointer New ()
Static Public Attributes
static const unsigned int InputImageDimension = InputImageType::ImageDimension
static const unsigned int OutputImageDimension = OutputImageType::ImageDimension
Static Public Attributes inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > >
static constexpr unsigned int OutputImageDimension
Protected Member Functions
DTIScalarMapsImageFilter ()
void DynamicThreadedGenerateData (const OutputImageRegionType &outputRegionForThread) ITK_OVERRIDE
virtual ~DTIScalarMapsImageFilter ()
Protected Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > >
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void GenerateData () ITK_OVERRIDE
unsigned int GetSafeThreadId ()
void IncrementNumberOfProcessedPoints ()
void InitializeZeroPixel (itk::Image< double, ImageDimension > *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
void InitializeZeroPixel (itk::Image< double, ImageDimension > *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
NumberedThreadImageToImageFilter ()
void SafeReleaseThreadId (unsigned int threadId)
virtual void ThreadProcessSlices ()
virtual ~NumberedThreadImageToImageFilter ()
Additional Inherited Members
Static Protected Member Functions inherited from anima::NumberedThreadImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > >
static ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<unsigned int ImageDimension = 3>
class anima::DTIScalarMapsImageFilter< ImageDimension >
Applies an variance filter to an image.
Computes tow image where a given pixel is the FA or ADC value of the tensor of the corresponding input pixel.
Definition at line 23 of file animaDTIScalarMapsImageFilter.h.
Member Typedef Documentation
ADCImageType
template<unsigned int ImageDimension = 3> typedef OutputImageType anima::DTIScalarMapsImageFilter< ImageDimension >::ADCImageType
Definition at line 33 of file animaDTIScalarMapsImageFilter.h.
ConstPointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<const Self> anima::DTIScalarMapsImageFilter< ImageDimension >::ConstPointer
Definition at line 46 of file animaDTIScalarMapsImageFilter.h.
FAImageType
template<unsigned int ImageDimension = 3> typedef OutputImageType anima::DTIScalarMapsImageFilter< ImageDimension >::FAImageType
Definition at line 32 of file animaDTIScalarMapsImageFilter.h.
InputImageType
template<unsigned int ImageDimension = 3> typedef itk::VectorImage<double, ImageDimension> anima::DTIScalarMapsImageFilter< ImageDimension >::InputImageType
Convenient typedefs for simplifying declarations.
Definition at line 29 of file animaDTIScalarMapsImageFilter.h.
OutputImageRegionType
template<unsigned int ImageDimension = 3> typedef OutputImageType::RegionType anima::DTIScalarMapsImageFilter< ImageDimension >::OutputImageRegionType
Definition at line 58 of file animaDTIScalarMapsImageFilter.h.
OutputImageType
template<unsigned int ImageDimension = 3> typedef itk::Image<double, ImageDimension> anima::DTIScalarMapsImageFilter< ImageDimension >::OutputImageType
Definition at line 30 of file animaDTIScalarMapsImageFilter.h.
Pointer
template<unsigned int ImageDimension = 3> typedef itk::SmartPointer<Self> anima::DTIScalarMapsImageFilter< ImageDimension >::Pointer
Definition at line 45 of file animaDTIScalarMapsImageFilter.h.
Self
template<unsigned int ImageDimension = 3> typedef DTIScalarMapsImageFilter anima::DTIScalarMapsImageFilter< ImageDimension >::Self
Standard class typedefs.
Definition at line 43 of file animaDTIScalarMapsImageFilter.h.
Superclass
template<unsigned int ImageDimension = 3> typedef anima::NumberedThreadImageToImageFilter<InputImageType, OutputImageType> anima::DTIScalarMapsImageFilter< ImageDimension >::Superclass
Definition at line 44 of file animaDTIScalarMapsImageFilter.h.
TensorImageRegionType
template<unsigned int ImageDimension = 3> typedef TensorImageType::RegionType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorImageRegionType
Definition at line 57 of file animaDTIScalarMapsImageFilter.h.
TensorImageSizeType
template<unsigned int ImageDimension = 3> typedef TensorImageType::SizeType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorImageSizeType
Definition at line 59 of file animaDTIScalarMapsImageFilter.h.
TensorImageType
template<unsigned int ImageDimension = 3> typedef InputImageType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorImageType
Definition at line 31 of file animaDTIScalarMapsImageFilter.h.
TensorVectorType
template<unsigned int ImageDimension = 3> typedef TensorImageType::PixelType anima::DTIScalarMapsImageFilter< ImageDimension >::TensorVectorType
Image typedef support.
Definition at line 55 of file animaDTIScalarMapsImageFilter.h.
Constructor & Destructor Documentation
DTIScalarMapsImageFilter()
template<unsigned int ImageDimension> anima::DTIScalarMapsImageFilter< ImageDimension >::DTIScalarMapsImageFilter () protected
Definition at line 21 of file animaDTIScalarMapsImageFilter.hxx.
Referenced by anima::DTIScalarMapsImageFilter< ImageDimension >::GetRadialDiffusivityImage().
~DTIScalarMapsImageFilter()
template<unsigned int ImageDimension = 3> virtual anima::DTIScalarMapsImageFilter< ImageDimension >::~DTIScalarMapsImageFilter () inline protected virtual
Definition at line 71 of file animaDTIScalarMapsImageFilter.h.
References anima::DTIScalarMapsImageFilter< ImageDimension >::DynamicThreadedGenerateData().
Member Function Documentation
CreateAnother()
template<unsigned int ImageDimension = 3> virtual::itk::LightObject::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::CreateAnother (void) const
DynamicThreadedGenerateData()
template<unsigned int ImageDimension> void anima::DTIScalarMapsImageFilter< ImageDimension >::DynamicThreadedGenerateData (const OutputImageRegionType & outputRegionForThread) protected
Definition at line 44 of file animaDTIScalarMapsImageFilter.hxx.
References anima::GetTensorFromVectorRepresentation().
Referenced by anima::DTIScalarMapsImageFilter< ImageDimension >::MakeOutput(), and anima::DTIScalarMapsImageFilter< ImageDimension >::~DTIScalarMapsImageFilter().
GetADCImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetADCImage () inline
Definition at line 64 of file animaDTIScalarMapsImageFilter.h.
GetAxialDiffusivityImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetAxialDiffusivityImage () inline
Definition at line 66 of file animaDTIScalarMapsImageFilter.h.
GetFAImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetFAImage () inline
Definition at line 65 of file animaDTIScalarMapsImageFilter.h.
GetNameOfClass()
template<unsigned int ImageDimension = 3> virtual const char* anima::DTIScalarMapsImageFilter< ImageDimension >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented from anima::NumberedThreadImageToImageFilter< itk::VectorImage< double, ImageDimension >, itk::Image< double, ImageDimension > >.
GetRadialDiffusivityImage()
template<unsigned int ImageDimension = 3> OutputImageType::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::GetRadialDiffusivityImage () inline
Definition at line 67 of file animaDTIScalarMapsImageFilter.h.
References anima::DTIScalarMapsImageFilter< ImageDimension >::DTIScalarMapsImageFilter().
MakeOutput()
template<unsigned int ImageDimension> itk::DataObject::Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::MakeOutput (itk::ProcessObject::DataObjectPointerArraySizeType idx)
Create the Output
Make Ouput
Definition at line 36 of file animaDTIScalarMapsImageFilter.hxx.
References anima::DTIScalarMapsImageFilter< ImageDimension >::DynamicThreadedGenerateData().
New()
template<unsigned int ImageDimension = 3> static Pointer anima::DTIScalarMapsImageFilter< ImageDimension >::New () static
Method for creation through the object factory.
Member Data Documentation
InputImageDimension
template<unsigned int ImageDimension = 3> const unsigned int anima::DTIScalarMapsImageFilter< ImageDimension >::InputImageDimension = InputImageType::ImageDimension static
Extract dimension from input and output image.
Definition at line 37 of file animaDTIScalarMapsImageFilter.h.
OutputImageDimension
template<unsigned int ImageDimension = 3> const unsigned int anima::DTIScalarMapsImageFilter< ImageDimension >::OutputImageDimension = OutputImageType::ImageDimension static
Definition at line 39 of file animaDTIScalarMapsImageFilter.h.
The documentation for this class was generated from the following files:
animaDTIScalarMapsImageFilter.h
animaDTIScalarMapsImageFilter.hxx