ANIMA: anima::B1GMMRelaxometryCostFunction Class Reference
anima::B1GMMRelaxometryCostFunction Class Reference
Cost function for estimating B1 from T2 relaxometry acquisition, following a multi-T2 EPG decay model. The cost function includes (via variable projection) estimation of compartment weights.
#include <animaB1GMMRelaxometryCostFunction.h>
Public Types
typedef std::vector< std::complex< double > > ComplexVectorType
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::DerivativeType DerivativeType
typedef std::vector< ComplexVectorType > MatrixType
typedef Superclass::MeasureType MeasureType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef B1GMMRelaxometryCostFunction Self
typedef itk::SingleValuedCostFunction Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual void GetDerivative (const ParametersType &parameters, DerivativeType &derivative) const ITK_OVERRIDE
virtual const char * GetNameOfClass () const
unsigned int GetNumberOfParameters () const ITK_OVERRIDE
ParametersType & GetOptimalT2Weights ()
virtual double GetSigmaSquare ()
virtual MeasureType GetValue (const ParametersType &parameters) const ITK_OVERRIDE
virtual void SetEchoSpacing (double _arg)
virtual void SetExcitationFlipAngle (double _arg)
virtual void SetGaussianIntegralTolerance (double _arg)
void SetGaussianMeans (std::vector< double > &val)
void SetGaussianVariances (std::vector< double > &val)
virtual void SetT1Value (double _arg)
void SetT2RelaxometrySignals (ParametersType &relaxoSignals)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
B1GMMRelaxometryCostFunction ()
void PrepareDataForLLS () const
void SolveLinearLeastSquares () const
Computes maximum likelihood estimates of weights.
virtual ~B1GMMRelaxometryCostFunction ()
Detailed Description
Cost function for estimating B1 from T2 relaxometry acquisition, following a multi-T2 EPG decay model. The cost function includes (via variable projection) estimation of compartment weights.
Definition at line 20 of file animaB1GMMRelaxometryCostFunction.h.
Member Typedef Documentation
ComplexVectorType
typedef std::vector< std::complex <double> > anima::B1GMMRelaxometryCostFunction::ComplexVectorType
Definition at line 38 of file animaB1GMMRelaxometryCostFunction.h.
ConstPointer
typedef itk::SmartPointer<const Self> anima::B1GMMRelaxometryCostFunction::ConstPointer
Definition at line 28 of file animaB1GMMRelaxometryCostFunction.h.
DerivativeType
typedef Superclass::DerivativeType anima::B1GMMRelaxometryCostFunction::DerivativeType
Definition at line 36 of file animaB1GMMRelaxometryCostFunction.h.
MatrixType
typedef std::vector<ComplexVectorType> anima::B1GMMRelaxometryCostFunction::MatrixType
Definition at line 39 of file animaB1GMMRelaxometryCostFunction.h.
MeasureType
typedef Superclass::MeasureType anima::B1GMMRelaxometryCostFunction::MeasureType
Definition at line 35 of file animaB1GMMRelaxometryCostFunction.h.
ParametersType
typedef Superclass::ParametersType anima::B1GMMRelaxometryCostFunction::ParametersType
Definition at line 37 of file animaB1GMMRelaxometryCostFunction.h.
Pointer
typedef itk::SmartPointer<Self> anima::B1GMMRelaxometryCostFunction::Pointer
Definition at line 27 of file animaB1GMMRelaxometryCostFunction.h.
Self
typedef B1GMMRelaxometryCostFunction anima::B1GMMRelaxometryCostFunction::Self
Standard class typedefs.
Definition at line 25 of file animaB1GMMRelaxometryCostFunction.h.
Superclass
typedef itk::SingleValuedCostFunction anima::B1GMMRelaxometryCostFunction::Superclass
Definition at line 26 of file animaB1GMMRelaxometryCostFunction.h.
Constructor & Destructor Documentation
B1GMMRelaxometryCostFunction()
anima::B1GMMRelaxometryCostFunction::B1GMMRelaxometryCostFunction () inline protected
Definition at line 63 of file animaB1GMMRelaxometryCostFunction.h.
References anima::NNLSOptimizer::New().
~B1GMMRelaxometryCostFunction()
virtual anima::B1GMMRelaxometryCostFunction::~B1GMMRelaxometryCostFunction () inline protected virtual
Definition at line 72 of file animaB1GMMRelaxometryCostFunction.h.
Member Function Documentation
CreateAnother()
virtual::itk::LightObject::Pointer anima::B1GMMRelaxometryCostFunction::CreateAnother (void) const
GetDerivative()
void anima::B1GMMRelaxometryCostFunction::GetDerivative (const ParametersType & parameters, DerivativeType & derivative) const virtual
Definition at line 27 of file animaB1GMMRelaxometryCostFunction.cxx.
GetNameOfClass()
virtual const char* anima::B1GMMRelaxometryCostFunction::GetNameOfClass () const virtual
Run-time type information (and related methods).
GetNumberOfParameters()
unsigned int anima::B1GMMRelaxometryCostFunction::GetNumberOfParameters () const inline
Definition at line 54 of file animaB1GMMRelaxometryCostFunction.h.
Referenced by GetValue().
GetOptimalT2Weights()
ParametersType& anima::B1GMMRelaxometryCostFunction::GetOptimalT2Weights () inline
Definition at line 60 of file animaB1GMMRelaxometryCostFunction.h.
GetSigmaSquare()
virtual double anima::B1GMMRelaxometryCostFunction::GetSigmaSquare () virtual
GetValue()
B1GMMRelaxometryCostFunction::MeasureType anima::B1GMMRelaxometryCostFunction::GetValue (const ParametersType & parameters) const virtual
Definition at line 12 of file animaB1GMMRelaxometryCostFunction.cxx.
References GetNumberOfParameters(), PrepareDataForLLS(), and SolveLinearLeastSquares().
New()
static Pointer anima::B1GMMRelaxometryCostFunction::New () static
PrepareDataForLLS()
void anima::B1GMMRelaxometryCostFunction::PrepareDataForLLS () const protected
Definition at line 34 of file animaB1GMMRelaxometryCostFunction.cxx.
References anima::GaussLaguerreQuadrature::GetIntegralValue(), anima::CholeskyDecomposition::PerformDecomposition(), anima::B1GMMDistributionIntegrand::SetEchoNumber(), anima::EPGSignalSimulator::SetEchoSpacing(), anima::EPGSignalSimulator::SetExcitationFlipAngle(), anima::B1GMMDistributionIntegrand::SetFlipAngle(), anima::B1GMMDistributionIntegrand::SetGaussianMean(), anima::B1GMMDistributionIntegrand::SetGaussianVariance(), anima::CholeskyDecomposition::SetInputMatrix(), anima::GaussLaguerreQuadrature::SetInterestZone(), anima::EPGSignalSimulator::SetNumberOfEchoes(), anima::B1GMMDistributionIntegrand::SetT1Value(), and anima::CholeskyDecomposition::SolveLinearSystem().
Referenced by GetValue().
SetEchoSpacing()
virtual void anima::B1GMMRelaxometryCostFunction::SetEchoSpacing (double _arg) virtual
SetExcitationFlipAngle()
virtual void anima::B1GMMRelaxometryCostFunction::SetExcitationFlipAngle (double _arg) virtual
SetGaussianIntegralTolerance()
virtual void anima::B1GMMRelaxometryCostFunction::SetGaussianIntegralTolerance (double _arg) virtual
SetGaussianMeans()
void anima::B1GMMRelaxometryCostFunction::SetGaussianMeans (std::vector< double > & val) inline
Definition at line 50 of file animaB1GMMRelaxometryCostFunction.h.
SetGaussianVariances()
void anima::B1GMMRelaxometryCostFunction::SetGaussianVariances (std::vector< double > & val) inline
Definition at line 51 of file animaB1GMMRelaxometryCostFunction.h.
SetT1Value()
virtual void anima::B1GMMRelaxometryCostFunction::SetT1Value (double _arg) virtual
SetT2RelaxometrySignals()
void anima::B1GMMRelaxometryCostFunction::SetT2RelaxometrySignals (ParametersType & relaxoSignals) inline
Definition at line 47 of file animaB1GMMRelaxometryCostFunction.h.
SolveLinearLeastSquares()
void anima::B1GMMRelaxometryCostFunction::SolveLinearLeastSquares () const protected
Computes maximum likelihood estimates of weights.
Definition at line 126 of file animaB1GMMRelaxometryCostFunction.cxx.
Referenced by GetValue().
The documentation for this class was generated from the following files:
animaB1GMMRelaxometryCostFunction.h
animaB1GMMRelaxometryCostFunction.cxx