ANIMA: anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage > Class Template Reference
anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage > Class Template Reference
Implements a class to handle thread number in a dynamic way for multithreaded methods needing thread numbering even for dynamic threading.
#include <animaNumberedThreadImageToImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef itk::SmartPointer< Self > Pointer
typedef NumberedThreadImageToImageFilter Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::ImageSource< TOutputImage >::ThreadStruct ThreadStruct
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual OutputImageRegionType GetComputationRegion ()
virtual const char * GetNameOfClass () const
virtual void SetComputationRegion (OutputImageRegionType _arg)
virtual void SetNumberOfPointsToProcess (unsigned int _arg)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static constexpr unsigned int OutputImageDimension = TOutputImage::ImageDimension
Protected Member Functions
virtual void BeforeThreadedGenerateData () ITK_OVERRIDE
virtual void GenerateData () ITK_OVERRIDE
unsigned int GetSafeThreadId ()
void IncrementNumberOfProcessedPoints ()
template<typename ScalarRealType >
void InitializeZeroPixel (TOutputImage *image, itk::VariableLengthVector< ScalarRealType > &zeroPixel)
Utility function to initialize output images pixel to zero for vector images.
template<typename PixelType >
void InitializeZeroPixel (TOutputImage *, PixelType &zeroPixel)
Utility function to initialize output images pixel to zero for all images except vector images.
NumberedThreadImageToImageFilter ()
void SafeReleaseThreadId (unsigned int threadId)
virtual void ThreadProcessSlices ()
virtual ~NumberedThreadImageToImageFilter ()
Static Protected Member Functions
static ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION ThreaderMultiSplitCallback (void *arg)
Detailed Description
template<typename TInputImage, typename TOutputImage>
class anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >
Implements a class to handle thread number in a dynamic way for multithreaded methods needing thread numbering even for dynamic threading.
Definition at line 15 of file animaNumberedThreadImageToImageFilter.h.
Member Typedef Documentation
ConstPointer
template<typename TInputImage, typename TOutputImage> typedef itk::SmartPointer<const Self> anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::ConstPointer
Definition at line 23 of file animaNumberedThreadImageToImageFilter.h.
OutputImageRegionType
template<typename TInputImage, typename TOutputImage> typedef Superclass::OutputImageRegionType anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::OutputImageRegionType
Definition at line 27 of file animaNumberedThreadImageToImageFilter.h.
Pointer
template<typename TInputImage, typename TOutputImage> typedef itk::SmartPointer<Self> anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::Pointer
Definition at line 22 of file animaNumberedThreadImageToImageFilter.h.
Self
template<typename TInputImage, typename TOutputImage> typedef NumberedThreadImageToImageFilter anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::Self
Standard class typedefs.
Definition at line 20 of file animaNumberedThreadImageToImageFilter.h.
Superclass
template<typename TInputImage, typename TOutputImage> typedef itk::ImageToImageFilter<TInputImage, TOutputImage> anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::Superclass
Definition at line 21 of file animaNumberedThreadImageToImageFilter.h.
ThreadStruct
template<typename TInputImage, typename TOutputImage> typedef itk::ImageSource<TOutputImage>::ThreadStruct anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::ThreadStruct
Definition at line 24 of file animaNumberedThreadImageToImageFilter.h.
Constructor & Destructor Documentation
NumberedThreadImageToImageFilter()
template<typename TInputImage, typename TOutputImage> anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::NumberedThreadImageToImageFilter () inline protected
Definition at line 41 of file animaNumberedThreadImageToImageFilter.h.
~NumberedThreadImageToImageFilter()
template<typename TInputImage, typename TOutputImage> virtual anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::~NumberedThreadImageToImageFilter () inline protected virtual
Definition at line 49 of file animaNumberedThreadImageToImageFilter.h.
Member Function Documentation
BeforeThreadedGenerateData()
template<typename TInputImage , typename TOutputImage > void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::BeforeThreadedGenerateData () protected virtual
Reimplemented in anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >, anima::SegmentationMeasuresImageFilter< TLabelImage >, anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >, anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::NonLocalMeansImageFilter< TInputImage >, anima::PatientToGroupComparisonImageFilter< PixelScalarType >, anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >, anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::NoiseGeneratorImageFilter< ImageType >, anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >, anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >, anima::MaskedImageToImageFilter< TInputImage, TOutputImage >, anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >, anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >, anima::MaskedImageToImageFilter< TImageType, TImageType >, anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >, anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >, anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >, anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >, anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >, and anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >.
Definition at line 10 of file animaNumberedThreadImageToImageFilter.hxx.
Referenced by anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::~NumberedThreadImageToImageFilter().
CreateAnother()
template<typename TInputImage, typename TOutputImage> virtual::itk::LightObject::Pointer anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::CreateAnother (void) const
GenerateData()
template<typename TInputImage , typename TOutputImage > void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::GenerateData () protected virtual
Definition at line 48 of file animaNumberedThreadImageToImageFilter.hxx.
Referenced by anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::~NumberedThreadImageToImageFilter().
GetComputationRegion()
template<typename TInputImage, typename TOutputImage> virtual OutputImageRegionType anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::GetComputationRegion () virtual
GetNameOfClass()
template<typename TInputImage, typename TOutputImage> virtual const char* anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::GetNameOfClass () const virtual
Run-time type information (and related methods)
Reimplemented in anima::MCMEstimatorImageFilter< InputPixelType, OutputPixelType >, anima::SegmentationMeasuresImageFilter< TLabelImage >, anima::DTIScalarMapsImageFilter< ImageDimension >, anima::NonLocalMeansImageFilter< TInputImage >, anima::MultiT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::OrientedModelBaseResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::PatientToGroupComparisonImageFilter< PixelScalarType >, anima::FlipTensorImageFilter< TPixelType, TImageDimension >, anima::MCMResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::GammaMixtureT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::DTIEstimationImageFilter< InputPixelScalarType, OutputPixelScalarType >, anima::NoiseGeneratorImageFilter< ImageType >, anima::ODFResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::GMMT2RelaxometryEstimationImageFilter< TPixelScalarType >, anima::TensorResampleImageFilter< TImageType, TInterpolatorPrecisionType >, anima::NLMeansPatientToGroupComparisonImageFilter< PixelScalarType >, anima::LocalPatchCovarianceDistanceImageFilter< PixelScalarType >, anima::LocalPatchMeanDistanceImageFilter< PixelScalarType >, anima::PatientToGroupODFComparisonImageFilter< PixelScalarType >, anima::MaskedImageToImageFilter< TInputImage, TOutputImage >, anima::T2RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::MaskedImageToImageFilter< itk::Image< InputPixelType, 3 >, anima::MCMImage< OutputPixelType, 3 > >, anima::MaskedImageToImageFilter< itk::VectorImage< TPixelType, TImageDimension >, itk::VectorImage< TPixelType, TImageDimension > >, anima::MaskedImageToImageFilter< TImageType, TImageType >, anima::MaskedImageToImageFilter< itk::Image< InputPixelScalarType, 3 >, itk::VectorImage< OutputPixelScalarType, 3 > >, anima::MaskedImageToImageFilter< itk::Image< TPixelScalarType, 3 >, itk::Image< TPixelScalarType, 3 > >, anima::MaskedImageToImageFilter< itk::VectorImage< PixelScalarType, 3 >, itk::Image< PixelScalarType, 3 > >, anima::T1RelaxometryEstimationImageFilter< TInputImage, TOutputImage >, anima::T1SERelaxometryEstimationImageFilter< TInputImage, TOutputImage >, and anima::T2EPGRelaxometryEstimationImageFilter< TInputImage, TOutputImage >.
GetSafeThreadId()
template<typename TInputImage , typename TOutputImage > unsigned int anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::GetSafeThreadId () protected
Definition at line 129 of file animaNumberedThreadImageToImageFilter.hxx.
Referenced by anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::~NumberedThreadImageToImageFilter().
IncrementNumberOfProcessedPoints()
template<typename TInputImage , typename TOutputImage > void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::IncrementNumberOfProcessedPoints () protected
Definition at line 114 of file animaNumberedThreadImageToImageFilter.hxx.
Referenced by anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::~NumberedThreadImageToImageFilter().
InitializeZeroPixel() [1/2]
template<typename TInputImage, typename TOutputImage> template<typename ScalarRealType > void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::InitializeZeroPixel (TOutputImage * image, itk::VariableLengthVector< ScalarRealType > & zeroPixel) inline protected
Utility function to initialize output images pixel to zero for vector images.
Definition at line 66 of file animaNumberedThreadImageToImageFilter.h.
InitializeZeroPixel() [2/2]
template<typename TInputImage, typename TOutputImage> template<typename PixelType > void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::InitializeZeroPixel (TOutputImage * , PixelType & zeroPixel) inline protected
Utility function to initialize output images pixel to zero for all images except vector images.
Definition at line 76 of file animaNumberedThreadImageToImageFilter.h.
New()
template<typename TInputImage, typename TOutputImage> static Pointer anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::New () static
Method for creation through the object factory.
SafeReleaseThreadId()
template<typename TInputImage , typename TOutputImage > void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::SafeReleaseThreadId (unsigned int threadId) protected
Definition at line 161 of file animaNumberedThreadImageToImageFilter.hxx.
Referenced by anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::~NumberedThreadImageToImageFilter().
SetComputationRegion()
template<typename TInputImage, typename TOutputImage> virtual void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::SetComputationRegion (OutputImageRegionType _arg) virtual
SetNumberOfPointsToProcess()
template<typename TInputImage, typename TOutputImage> virtual void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::SetNumberOfPointsToProcess (unsigned int _arg) virtual
ThreaderMultiSplitCallback()
template<typename TInputImage , typename TOutputImage > ITK_THREAD_RETURN_FUNCTION_CALL_CONVENTION anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::ThreaderMultiSplitCallback (void * arg) static protected
Definition at line 69 of file animaNumberedThreadImageToImageFilter.hxx.
Referenced by anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::~NumberedThreadImageToImageFilter().
ThreadProcessSlices()
template<typename TInputImage , typename TOutputImage > void anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::ThreadProcessSlices () protected virtual
Definition at line 84 of file animaNumberedThreadImageToImageFilter.hxx.
Referenced by anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::ThreaderMultiSplitCallback(), and anima::NumberedThreadImageToImageFilter< ImageType, ImageType >::~NumberedThreadImageToImageFilter().
Member Data Documentation
OutputImageDimension
template<typename TInputImage, typename TOutputImage> constexpr unsigned int anima::NumberedThreadImageToImageFilter< TInputImage, TOutputImage >::OutputImageDimension = TOutputImage::ImageDimension static
Definition at line 26 of file animaNumberedThreadImageToImageFilter.h.
The documentation for this class was generated from the following files:
animaNumberedThreadImageToImageFilter.h
animaNumberedThreadImageToImageFilter.hxx