ANIMA: anima::RootFindingFunctionBoostBridge Class Reference
anima::RootFindingFunctionBoostBridge Class Reference
#include <animaBaseRootFindingAlgorithm.h>
Public Types
using BaseCostFunctionPointer = BaseCostFunctionType::Pointer
using BaseCostFunctionType = itk::SingleValuedCostFunction
using ParametersType = BaseCostFunctionType::ParametersType
Public Member Functions
double operator() (const double &x)
RootFindingFunctionBoostBridge ()
void SetRootFindingFunction (BaseCostFunctionType *f)
Detailed Description
Definition at line 26 of file animaBaseRootFindingAlgorithm.h.
Member Typedef Documentation
BaseCostFunctionPointer
using anima::RootFindingFunctionBoostBridge::BaseCostFunctionPointer = BaseCostFunctionType::Pointer
Definition at line 30 of file animaBaseRootFindingAlgorithm.h.
BaseCostFunctionType
using anima::RootFindingFunctionBoostBridge::BaseCostFunctionType = itk::SingleValuedCostFunction
Definition at line 29 of file animaBaseRootFindingAlgorithm.h.
ParametersType
using anima::RootFindingFunctionBoostBridge::ParametersType = BaseCostFunctionType::ParametersType
Definition at line 31 of file animaBaseRootFindingAlgorithm.h.
Constructor & Destructor Documentation
RootFindingFunctionBoostBridge()
anima::RootFindingFunctionBoostBridge::RootFindingFunctionBoostBridge () inline
Definition at line 37 of file animaBaseRootFindingAlgorithm.h.
Member Function Documentation
operator()()
double anima::RootFindingFunctionBoostBridge::operator() (const double & x)
Definition at line 11 of file animaBaseRootFindingAlgorithm.cxx.
SetRootFindingFunction()
void anima::RootFindingFunctionBoostBridge::SetRootFindingFunction (BaseCostFunctionType * f) inline
Definition at line 35 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BoostBisectionRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), and anima::BracketAndSolveRootFindingAlgorithm::Optimize().
The documentation for this class was generated from the following files:
animaBaseRootFindingAlgorithm.h
animaBaseRootFindingAlgorithm.cxx