ANIMA: anima::B1GammaDerivativeDistributionIntegrand Class Reference
anima::B1GammaDerivativeDistributionIntegrand Class Reference
Integrand to compute the internal derivative integral per distribution in B1GammaMixtureT2RelaxometryCostFunction.
#include <animaB1GammaDerivativeDistributionIntegrand.h>
Public Types
using Superclass = B1GammaDistributionIntegrand
Public Types inherited from anima::B1GammaDistributionIntegrand
using EPGVectorsMapType = std::map< double, anima::EPGSignalSimulator::RealVectorType >
Public Member Functions
B1GammaDerivativeDistributionIntegrand (anima::EPGSignalSimulator &sigSim, EPGVectorsMapType &val, EPGVectorsMapType &derVal)
virtual double operator() (double const t) override
void SetB1DerivativeFlag (bool val)
Public Member Functions inherited from anima::B1GammaDistributionIntegrand
B1GammaDistributionIntegrand (anima::EPGSignalSimulator &sigSim, EPGVectorsMapType &val)
void SetEchoNumber (unsigned int val)
void SetFlipAngle (double val)
void SetGammaMean (double val)
void SetGammaVariance (double val)
void SetT1Value (double val)
Additional Inherited Members
Protected Attributes inherited from anima::B1GammaDistributionIntegrand
unsigned int m_EchoNumber
anima::EPGSignalSimulator & m_EPGSimulator
EPG signal simulator reference: instantiated outside.
EPGVectorsMapType & m_EPGVectors
Since boost Gauss Legendre integration works on object copies, we need to keep a reference to EPG vectors, held externally.
double m_FlipAngle
double m_GammaMean
double m_GammaVariance
double m_T1Value
Detailed Description
Integrand to compute the internal derivative integral per distribution in B1GammaMixtureT2RelaxometryCostFunction.
Definition at line 17 of file animaB1GammaDerivativeDistributionIntegrand.h.
Member Typedef Documentation
Superclass
using anima::B1GammaDerivativeDistributionIntegrand::Superclass = B1GammaDistributionIntegrand
Definition at line 20 of file animaB1GammaDerivativeDistributionIntegrand.h.
Constructor & Destructor Documentation
B1GammaDerivativeDistributionIntegrand()
anima::B1GammaDerivativeDistributionIntegrand::B1GammaDerivativeDistributionIntegrand (anima::EPGSignalSimulator & sigSim, EPGVectorsMapType & val, EPGVectorsMapType & derVal) inline
Definition at line 21 of file animaB1GammaDerivativeDistributionIntegrand.h.
Member Function Documentation
operator()()
double anima::B1GammaDerivativeDistributionIntegrand::operator() (double const t) override virtual
Reimplemented from anima::B1GammaDistributionIntegrand.
Definition at line 8 of file animaB1GammaDerivativeDistributionIntegrand.cxx.
References anima::EPGSignalSimulator::GetFADerivative(), anima::EPGSignalSimulator::GetValue(), anima::B1GammaDistributionIntegrand::m_EchoNumber, anima::B1GammaDistributionIntegrand::m_EPGSimulator, anima::B1GammaDistributionIntegrand::m_EPGVectors, anima::B1GammaDistributionIntegrand::m_FlipAngle, anima::B1GammaDistributionIntegrand::m_GammaMean, anima::B1GammaDistributionIntegrand::m_GammaVariance, and anima::B1GammaDistributionIntegrand::m_T1Value.
SetB1DerivativeFlag()
void anima::B1GammaDerivativeDistributionIntegrand::SetB1DerivativeFlag (bool val) inline
Definition at line 27 of file animaB1GammaDerivativeDistributionIntegrand.h.
Referenced by anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative().
The documentation for this class was generated from the following files:
animaB1GammaDerivativeDistributionIntegrand.h
animaB1GammaDerivativeDistributionIntegrand.cxx