ANIMA: anima::DirectionScaleSkewTransform< TScalarType > Class Template Reference
anima::DirectionScaleSkewTransform< TScalarType > Class Template Reference
#include <animaDirectionScaleSkewTransform.h>
Public Types
typedef Superclass::CenterType CenterType
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::Matrix< ScalarType, 4, 4 > HomogeneousMatrixType
typedef Superclass::InputCovariantVectorType InputCovariantVectorType
typedef Superclass::InputPointType InputPointType
typedef Superclass::InputVectorType InputVectorType
typedef Superclass::InputVnlVectorType InputVnlVectorType
typedef Superclass::InverseMatrixType InverseMatrixType
typedef Superclass::JacobianType JacobianType
typedef Superclass::MatrixType MatrixType
typedef Superclass::OffsetType OffsetType
typedef Superclass::OutputCovariantVectorType OutputCovariantVectorType
typedef Superclass::OutputPointType OutputPointType
typedef Superclass::OutputVectorType OutputVectorType
typedef Superclass::OutputVnlVectorType OutputVnlVectorType
typedef Superclass::ParametersType ParametersType
typedef itk::SmartPointer< Self > Pointer
typedef Superclass::ScalarType ScalarType
typedef DirectionScaleSkewTransform Self
typedef itk::MatrixOffsetTransformBase< TScalarType, 3 > Superclass
typedef Superclass::TranslationType TranslationType
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const ScalarType & GetLogFirstSkew () const
virtual const ScalarType & GetLogScale () const
virtual const ScalarType & GetLogSecondSkew () const
virtual const vnl_matrix< TScalarType > & GetLogTransform () const
virtual const itk::Vector< TScalarType, 12 > & GetLogVector () const
virtual const char * GetNameOfClass () const
virtual const ParametersType & GetParameters () const override
virtual const unsigned int & GetUniqueDirection () const
virtual const ScalarType & GetUniqueTranslation () const
virtual void SetGeometry (HomogeneousMatrixType &matrix, bool update=true)
virtual void SetIdentity () override
void SetLogFirstSkew (ScalarType skew, bool update=true)
void SetLogScale (ScalarType scale, bool update=true)
void SetLogSecondSkew (ScalarType skew, bool update=true)
virtual void SetParameters (const ParametersType &parameters) override
void SetUniqueDirection (unsigned int direction)
void SetUniqueTranslation (ScalarType translation, bool update=true)
Static Public Member Functions
static Pointer New ()
Static Public Attributes
static const unsigned int InputSpaceDimension = 3
static const unsigned int OutputSpaceDimension = 3
static const unsigned int ParametersDimension = 4
static const unsigned int SpaceDimension = 3
Protected Member Functions
virtual void ComputeMatrix () override
DirectionScaleSkewTransform ()
DirectionScaleSkewTransform (unsigned int ParamersDim)
virtual void GetInternalExponential ()
virtual void GetInternalLogarithm ()
virtual void InternalApplyGeometry (MatrixType &linearMatrix, OffsetType &offset)
void PrintSelf (std::ostream &os, itk::Indent indent) const override
~DirectionScaleSkewTransform ()
Protected Attributes
vnl_matrix< TScalarType > m_ExpTransform
HomogeneousMatrixType m_Geometry
HomogeneousMatrixType m_GeometryInv
vnl_matrix< TScalarType > m_LogTransform
Detailed Description
template<class TScalarType = double>
class anima::DirectionScaleSkewTransform< TScalarType >
Definition at line 10 of file animaDirectionScaleSkewTransform.h.
Member Typedef Documentation
CenterType
template<class TScalarType = double> typedef Superclass::CenterType anima::DirectionScaleSkewTransform< TScalarType >::CenterType
Definition at line 49 of file animaDirectionScaleSkewTransform.h.
ConstPointer
template<class TScalarType = double> typedef itk::SmartPointer<const Self> anima::DirectionScaleSkewTransform< TScalarType >::ConstPointer
Definition at line 18 of file animaDirectionScaleSkewTransform.h.
HomogeneousMatrixType
template<class TScalarType = double> typedef itk::Matrix<ScalarType,4,4> anima::DirectionScaleSkewTransform< TScalarType >::HomogeneousMatrixType
Definition at line 47 of file animaDirectionScaleSkewTransform.h.
InputCovariantVectorType
template<class TScalarType = double> typedef Superclass::InputCovariantVectorType anima::DirectionScaleSkewTransform< TScalarType >::InputCovariantVectorType
Definition at line 43 of file animaDirectionScaleSkewTransform.h.
InputPointType
template<class TScalarType = double> typedef Superclass::InputPointType anima::DirectionScaleSkewTransform< TScalarType >::InputPointType
Definition at line 36 of file animaDirectionScaleSkewTransform.h.
InputVectorType
template<class TScalarType = double> typedef Superclass::InputVectorType anima::DirectionScaleSkewTransform< TScalarType >::InputVectorType
Definition at line 38 of file animaDirectionScaleSkewTransform.h.
InputVnlVectorType
template<class TScalarType = double> typedef Superclass::InputVnlVectorType anima::DirectionScaleSkewTransform< TScalarType >::InputVnlVectorType
Definition at line 40 of file animaDirectionScaleSkewTransform.h.
InverseMatrixType
template<class TScalarType = double> typedef Superclass::InverseMatrixType anima::DirectionScaleSkewTransform< TScalarType >::InverseMatrixType
Definition at line 48 of file animaDirectionScaleSkewTransform.h.
JacobianType
template<class TScalarType = double> typedef Superclass::JacobianType anima::DirectionScaleSkewTransform< TScalarType >::JacobianType
Definition at line 34 of file animaDirectionScaleSkewTransform.h.
MatrixType
template<class TScalarType = double> typedef Superclass::MatrixType anima::DirectionScaleSkewTransform< TScalarType >::MatrixType
Definition at line 46 of file animaDirectionScaleSkewTransform.h.
OffsetType
template<class TScalarType = double> typedef Superclass::OffsetType anima::DirectionScaleSkewTransform< TScalarType >::OffsetType
Definition at line 50 of file animaDirectionScaleSkewTransform.h.
OutputCovariantVectorType
template<class TScalarType = double> typedef Superclass::OutputCovariantVectorType anima::DirectionScaleSkewTransform< TScalarType >::OutputCovariantVectorType
Definition at line 45 of file animaDirectionScaleSkewTransform.h.
OutputPointType
template<class TScalarType = double> typedef Superclass::OutputPointType anima::DirectionScaleSkewTransform< TScalarType >::OutputPointType
Definition at line 37 of file animaDirectionScaleSkewTransform.h.
OutputVectorType
template<class TScalarType = double> typedef Superclass::OutputVectorType anima::DirectionScaleSkewTransform< TScalarType >::OutputVectorType
Definition at line 39 of file animaDirectionScaleSkewTransform.h.
OutputVnlVectorType
template<class TScalarType = double> typedef Superclass::OutputVnlVectorType anima::DirectionScaleSkewTransform< TScalarType >::OutputVnlVectorType
Definition at line 41 of file animaDirectionScaleSkewTransform.h.
ParametersType
template<class TScalarType = double> typedef Superclass::ParametersType anima::DirectionScaleSkewTransform< TScalarType >::ParametersType
Parameters Type
Definition at line 33 of file animaDirectionScaleSkewTransform.h.
Pointer
template<class TScalarType = double> typedef itk::SmartPointer<Self> anima::DirectionScaleSkewTransform< TScalarType >::Pointer
Definition at line 17 of file animaDirectionScaleSkewTransform.h.
ScalarType
template<class TScalarType = double> typedef Superclass::ScalarType anima::DirectionScaleSkewTransform< TScalarType >::ScalarType
Definition at line 35 of file animaDirectionScaleSkewTransform.h.
Self
template<class TScalarType = double> typedef DirectionScaleSkewTransform anima::DirectionScaleSkewTransform< TScalarType >::Self
Standard class typedefs.
Definition at line 15 of file animaDirectionScaleSkewTransform.h.
Superclass
template<class TScalarType = double> typedef itk::MatrixOffsetTransformBase< TScalarType, 3 > anima::DirectionScaleSkewTransform< TScalarType >::Superclass
Definition at line 16 of file animaDirectionScaleSkewTransform.h.
TranslationType
template<class TScalarType = double> typedef Superclass::TranslationType anima::DirectionScaleSkewTransform< TScalarType >::TranslationType
Definition at line 51 of file animaDirectionScaleSkewTransform.h.
Constructor & Destructor Documentation
DirectionScaleSkewTransform() [1/2]
template<class TScalarType = double> anima::DirectionScaleSkewTransform< TScalarType >::DirectionScaleSkewTransform () inline protected
Definition at line 79 of file animaDirectionScaleSkewTransform.h.
DirectionScaleSkewTransform() [2/2]
template<class TScalarType = double> anima::DirectionScaleSkewTransform< TScalarType >::DirectionScaleSkewTransform (unsigned int ParamersDim) inline protected
Definition at line 85 of file animaDirectionScaleSkewTransform.h.
~DirectionScaleSkewTransform()
template<class TScalarType = double> anima::DirectionScaleSkewTransform< TScalarType >::~DirectionScaleSkewTransform () inline protected
Definition at line 91 of file animaDirectionScaleSkewTransform.h.
References anima::DirectionScaleSkewTransform< TScalarType >::ComputeMatrix(), anima::DirectionScaleSkewTransform< TScalarType >::GetInternalExponential(), anima::DirectionScaleSkewTransform< TScalarType >::GetInternalLogarithm(), anima::DirectionScaleSkewTransform< TScalarType >::InternalApplyGeometry(), and anima::DirectionScaleSkewTransform< TScalarType >::PrintSelf().
Member Function Documentation
ComputeMatrix()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::ComputeMatrix (void) override protected virtual
Definition at line 122 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::InternalApplyGeometry().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetUniqueDirection(), and anima::DirectionScaleSkewTransform< TScalarType >::~DirectionScaleSkewTransform().
CreateAnother()
template<class TScalarType = double> virtual::itk::LightObject::Pointer anima::DirectionScaleSkewTransform< TScalarType >::CreateAnother (void) const
GetInternalExponential()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::GetInternalExponential () protected virtual
Reimplemented in anima::DirectionTransform< TScalarType >, and anima::DirectionScaleTransform< TScalarType >.
Definition at line 230 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::PrintSelf().
Referenced by anima::DirectionScaleTransform< TScalarType >::DirectionScaleTransform(), anima::DirectionTransform< TScalarType >::DirectionTransform(), anima::DirectionScaleSkewTransform< TScalarType >::GetInternalLogarithm(), and anima::DirectionScaleSkewTransform< TScalarType >::~DirectionScaleSkewTransform().
GetInternalLogarithm()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::GetInternalLogarithm () protected virtual
Reimplemented in anima::DirectionTransform< TScalarType >, and anima::DirectionScaleTransform< TScalarType >.
Definition at line 208 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::GetInternalExponential().
Referenced by anima::DirectionScaleTransform< TScalarType >::DirectionScaleTransform(), anima::DirectionTransform< TScalarType >::DirectionTransform(), anima::DirectionScaleSkewTransform< TScalarType >::InternalApplyGeometry(), and anima::DirectionScaleSkewTransform< TScalarType >::~DirectionScaleSkewTransform().
GetLogFirstSkew()
template<class TScalarType = double> virtual const ScalarType& anima::DirectionScaleSkewTransform< TScalarType >::GetLogFirstSkew () const virtual
GetLogScale()
template<class TScalarType = double> virtual const ScalarType& anima::DirectionScaleSkewTransform< TScalarType >::GetLogScale () const virtual
GetLogSecondSkew()
template<class TScalarType = double> virtual const ScalarType& anima::DirectionScaleSkewTransform< TScalarType >::GetLogSecondSkew () const virtual
GetLogTransform()
template<class TScalarType = double> virtual const vnl_matrix<TScalarType>& anima::DirectionScaleSkewTransform< TScalarType >::GetLogTransform () const inline virtual
Definition at line 76 of file animaDirectionScaleSkewTransform.h.
References anima::DirectionScaleSkewTransform< TScalarType >::m_LogTransform.
GetLogVector()
template<class TScalarType = double> virtual const itk::Vector<TScalarType,12>& anima::DirectionScaleSkewTransform< TScalarType >::GetLogVector () const inline virtual
Definition at line 75 of file animaDirectionScaleSkewTransform.h.
GetNameOfClass()
template<class TScalarType = double> virtual const char* anima::DirectionScaleSkewTransform< TScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods).
Reimplemented in anima::DirectionTransform< TScalarType >, and anima::DirectionScaleTransform< TScalarType >.
GetParameters()
template<class TScalarType > const DirectionScaleSkewTransform< TScalarType >::ParametersType & anima::DirectionScaleSkewTransform< TScalarType >::GetParameters (void) const override virtual
Reimplemented in anima::DirectionTransform< TScalarType >, and anima::DirectionScaleTransform< TScalarType >.
Definition at line 27 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::SetIdentity().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetParameters().
GetUniqueDirection()
template<class TScalarType = double> virtual const unsigned int& anima::DirectionScaleSkewTransform< TScalarType >::GetUniqueDirection () const virtual
GetUniqueTranslation()
template<class TScalarType = double> virtual const ScalarType& anima::DirectionScaleSkewTransform< TScalarType >::GetUniqueTranslation () const virtual
InternalApplyGeometry()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::InternalApplyGeometry (MatrixType & linearMatrix, OffsetType & offset) protected virtual
Reimplemented in anima::DirectionTransform< TScalarType >, and anima::DirectionScaleTransform< TScalarType >.
Definition at line 146 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::GetInternalLogarithm().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::ComputeMatrix(), anima::DirectionScaleTransform< TScalarType >::DirectionScaleTransform(), anima::DirectionTransform< TScalarType >::DirectionTransform(), and anima::DirectionScaleSkewTransform< TScalarType >::~DirectionScaleSkewTransform().
New()
template<class TScalarType = double> static Pointer anima::DirectionScaleSkewTransform< TScalarType >::New () static
New macro for creation of through a Smart Pointer.
PrintSelf()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::PrintSelf (std::ostream & os, itk::Indent indent) const override protected
Definition at line 268 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleTransform< TScalarType >::SetParameters().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::GetInternalExponential(), and anima::DirectionScaleSkewTransform< TScalarType >::~DirectionScaleSkewTransform().
SetGeometry()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetGeometry (HomogeneousMatrixType & matrix, bool update = true) virtual
Definition at line 56 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::SetLogScale().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetIdentity().
SetIdentity()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetIdentity () override virtual
Definition at line 40 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::SetGeometry().
Referenced by anima::DistortionCorrectionBlockMatcher< TInputImageType >::BlockMatchingSetup(), and anima::DirectionScaleSkewTransform< TScalarType >::GetParameters().
SetLogFirstSkew()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetLogFirstSkew (ScalarType skew, bool update = true)
Definition at line 79 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::SetLogSecondSkew().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetLogScale().
SetLogScale()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetLogScale (ScalarType scale, bool update = true)
Definition at line 68 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::SetLogFirstSkew().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetGeometry().
SetLogSecondSkew()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetLogSecondSkew (ScalarType skew, bool update = true)
Definition at line 90 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::SetUniqueTranslation().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetLogFirstSkew().
SetParameters()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetParameters (const ParametersType & parameters) override virtual
Reimplemented in anima::DirectionTransform< TScalarType >, and anima::DirectionScaleTransform< TScalarType >.
Definition at line 11 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::GetParameters().
SetUniqueDirection()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetUniqueDirection (unsigned int direction)
Definition at line 112 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::ComputeMatrix().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetUniqueTranslation().
SetUniqueTranslation()
template<class TScalarType > void anima::DirectionScaleSkewTransform< TScalarType >::SetUniqueTranslation (ScalarType translation, bool update = true)
Definition at line 101 of file animaDirectionScaleSkewTransform.hxx.
References anima::DirectionScaleSkewTransform< TScalarType >::SetUniqueDirection().
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::SetLogSecondSkew().
Member Data Documentation
InputSpaceDimension
template<class TScalarType = double> const unsigned int anima::DirectionScaleSkewTransform< TScalarType >::InputSpaceDimension = 3 static
Definition at line 28 of file animaDirectionScaleSkewTransform.h.
m_ExpTransform
template<class TScalarType = double> vnl_matrix<TScalarType> anima::DirectionScaleSkewTransform< TScalarType >::m_ExpTransform protected
Definition at line 100 of file animaDirectionScaleSkewTransform.h.
m_Geometry
template<class TScalarType = double> HomogeneousMatrixType anima::DirectionScaleSkewTransform< TScalarType >::m_Geometry protected
Definition at line 101 of file animaDirectionScaleSkewTransform.h.
m_GeometryInv
template<class TScalarType = double> HomogeneousMatrixType anima::DirectionScaleSkewTransform< TScalarType >::m_GeometryInv protected
Definition at line 101 of file animaDirectionScaleSkewTransform.h.
m_LogTransform
template<class TScalarType = double> vnl_matrix<TScalarType> anima::DirectionScaleSkewTransform< TScalarType >::m_LogTransform protected
Definition at line 100 of file animaDirectionScaleSkewTransform.h.
Referenced by anima::DirectionScaleSkewTransform< TScalarType >::GetLogTransform().
OutputSpaceDimension
template<class TScalarType = double> const unsigned int anima::DirectionScaleSkewTransform< TScalarType >::OutputSpaceDimension = 3 static
Definition at line 29 of file animaDirectionScaleSkewTransform.h.
ParametersDimension
template<class TScalarType = double> const unsigned int anima::DirectionScaleSkewTransform< TScalarType >::ParametersDimension = 4 static
Definition at line 30 of file animaDirectionScaleSkewTransform.h.
SpaceDimension
template<class TScalarType = double> const unsigned int anima::DirectionScaleSkewTransform< TScalarType >::SpaceDimension = 3 static
Dimension of the space.
Definition at line 27 of file animaDirectionScaleSkewTransform.h.
The documentation for this class was generated from the following files:
animaDirectionScaleSkewTransform.h
animaDirectionScaleSkewTransform.hxx