ANIMA: anima::DekkerRootFindingAlgorithm Class Reference
anima::DekkerRootFindingAlgorithm Class Reference
#include <animaDekkerRootFindingAlgorithm.h>
Public Types
using ParametersType = Superclass::ParametersType
using Superclass = BaseRootFindingAlgorithm
Public Types inherited from anima::BaseRootFindingAlgorithm
using BaseCostFunctionPointer = BaseCostFunctionType::Pointer
using BaseCostFunctionType = itk::SingleValuedCostFunction
using ParametersType = BaseCostFunctionType::ParametersType
Public Member Functions
double Optimize () ITK_OVERRIDE
Public Member Functions inherited from anima::BaseRootFindingAlgorithm
BaseRootFindingAlgorithm ()
double GetCostFunctionTolerance ()
double GetFunctionValueAtInitialLowerBound ()
double GetFunctionValueAtInitialUpperBound ()
double GetLowerBound ()
unsigned int GetMaximumNumberOfIterations ()
bool GetProvidedFunctionValueAtInitialLowerBound ()
bool GetProvidedFunctionValueAtInitialUpperBound ()
BaseCostFunctionType * GetRootFindingFunction ()
double GetRootRelativeTolerance ()
double GetUpperBound ()
void SetCostFunctionTolerance (const double &val)
void SetFunctionValueAtInitialLowerBound (const double &val)
void SetFunctionValueAtInitialUpperBound (const double &val)
void SetLowerBound (const double &val)
void SetMaximumNumberOfIterations (const unsigned int &val)
void SetRootFindingFunction (BaseCostFunctionType *f)
void SetRootRelativeTolerance (const double &val)
void SetUpperBound (const double &val)
virtual ~BaseRootFindingAlgorithm ()
Detailed Description
Definition at line 9 of file animaDekkerRootFindingAlgorithm.h.
Member Typedef Documentation
ParametersType
using anima::DekkerRootFindingAlgorithm::ParametersType = Superclass::ParametersType
Definition at line 13 of file animaDekkerRootFindingAlgorithm.h.
Superclass
using anima::DekkerRootFindingAlgorithm::Superclass = BaseRootFindingAlgorithm
Definition at line 12 of file animaDekkerRootFindingAlgorithm.h.
Member Function Documentation
Optimize()
double anima::DekkerRootFindingAlgorithm::Optimize () virtual
Implements anima::BaseRootFindingAlgorithm.
Definition at line 6 of file animaDekkerRootFindingAlgorithm.cxx.
References anima::BaseRootFindingAlgorithm::GetCostFunctionTolerance(), anima::BaseRootFindingAlgorithm::GetFunctionValueAtInitialLowerBound(), anima::BaseRootFindingAlgorithm::GetFunctionValueAtInitialUpperBound(), anima::BaseRootFindingAlgorithm::GetLowerBound(), anima::BaseRootFindingAlgorithm::GetMaximumNumberOfIterations(), anima::BaseRootFindingAlgorithm::GetProvidedFunctionValueAtInitialLowerBound(), anima::BaseRootFindingAlgorithm::GetProvidedFunctionValueAtInitialUpperBound(), anima::BaseRootFindingAlgorithm::GetRootFindingFunction(), anima::BaseRootFindingAlgorithm::GetRootRelativeTolerance(), and anima::BaseRootFindingAlgorithm::GetUpperBound().
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
The documentation for this class was generated from the following files:
animaDekkerRootFindingAlgorithm.h
animaDekkerRootFindingAlgorithm.cxx