ANIMA: anima::MCMScalarMapsImageFilter< TPixelType > Class Template Reference
anima::MCMScalarMapsImageFilter< TPixelType > Class Template Reference
#include <animaMCMScalarMapsImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef InputImageType::ConstPointer InputImagePointer
typedef anima::MCMImage< TPixelType, 3 > InputImageType
typedef InputImageType::IndexType InputIndexType
typedef InputImageType::RegionType InputRegionType
typedef MCModelType::Pointer MCModelPointer
typedef anima::MultiCompartmentModel MCModelType
typedef OutputImageType::Pointer OutputImagePointer
typedef itk::Image< TPixelType, 3 > OutputImageType
typedef InputImageType::PixelType PixelType
typedef itk::SmartPointer< Self > Pointer
typedef MCMScalarMapsImageFilter Self
typedef itk::ImageToImageFilter< InputImageType, OutputImageType > Superclass
Public Member Functions
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
virtual void SetIncludeIsotropicWeights (bool _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void DynamicThreadedGenerateData (const InputRegionType &outputRegionForThread) ITK_OVERRIDE
template<class T >
bool isZero (const itk::VariableLengthVector< T > &value) const
MCMScalarMapsImageFilter ()
virtual ~MCMScalarMapsImageFilter ()
Detailed Description
template<class TPixelType>
class anima::MCMScalarMapsImageFilter< TPixelType >
Definition at line 12 of file animaMCMScalarMapsImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class TPixelType > typedef itk::SmartPointer<const Self> anima::MCMScalarMapsImageFilter< TPixelType >::ConstPointer
Definition at line 22 of file animaMCMScalarMapsImageFilter.h.
InputImagePointer
template<class TPixelType > typedef InputImageType::ConstPointer anima::MCMScalarMapsImageFilter< TPixelType >::InputImagePointer
Definition at line 30 of file animaMCMScalarMapsImageFilter.h.
InputImageType
template<class TPixelType > typedef anima::MCMImage<TPixelType, 3> anima::MCMScalarMapsImageFilter< TPixelType >::InputImageType
Definition at line 18 of file animaMCMScalarMapsImageFilter.h.
InputIndexType
template<class TPixelType > typedef InputImageType::IndexType anima::MCMScalarMapsImageFilter< TPixelType >::InputIndexType
Definition at line 34 of file animaMCMScalarMapsImageFilter.h.
InputRegionType
template<class TPixelType > typedef InputImageType::RegionType anima::MCMScalarMapsImageFilter< TPixelType >::InputRegionType
Definition at line 33 of file animaMCMScalarMapsImageFilter.h.
MCModelPointer
template<class TPixelType > typedef MCModelType::Pointer anima::MCMScalarMapsImageFilter< TPixelType >::MCModelPointer
Definition at line 39 of file animaMCMScalarMapsImageFilter.h.
MCModelType
template<class TPixelType > typedef anima::MultiCompartmentModel anima::MCMScalarMapsImageFilter< TPixelType >::MCModelType
Definition at line 38 of file animaMCMScalarMapsImageFilter.h.
OutputImagePointer
template<class TPixelType > typedef OutputImageType::Pointer anima::MCMScalarMapsImageFilter< TPixelType >::OutputImagePointer
Definition at line 31 of file animaMCMScalarMapsImageFilter.h.
OutputImageType
template<class TPixelType > typedef itk::Image<TPixelType, 3> anima::MCMScalarMapsImageFilter< TPixelType >::OutputImageType
Definition at line 19 of file animaMCMScalarMapsImageFilter.h.
PixelType
template<class TPixelType > typedef InputImageType::PixelType anima::MCMScalarMapsImageFilter< TPixelType >::PixelType
Definition at line 35 of file animaMCMScalarMapsImageFilter.h.
Pointer
template<class TPixelType > typedef itk::SmartPointer<Self> anima::MCMScalarMapsImageFilter< TPixelType >::Pointer
Definition at line 21 of file animaMCMScalarMapsImageFilter.h.
Self
template<class TPixelType > typedef MCMScalarMapsImageFilter anima::MCMScalarMapsImageFilter< TPixelType >::Self
Standard class typedefs
Definition at line 17 of file animaMCMScalarMapsImageFilter.h.
Superclass
template<class TPixelType > typedef itk::ImageToImageFilter<InputImageType, OutputImageType > anima::MCMScalarMapsImageFilter< TPixelType >::Superclass
Definition at line 20 of file animaMCMScalarMapsImageFilter.h.
Constructor & Destructor Documentation
MCMScalarMapsImageFilter()
template<class TPixelType > anima::MCMScalarMapsImageFilter< TPixelType >::MCMScalarMapsImageFilter () inline protected
Definition at line 44 of file animaMCMScalarMapsImageFilter.h.
~MCMScalarMapsImageFilter()
template<class TPixelType > virtual anima::MCMScalarMapsImageFilter< TPixelType >::~MCMScalarMapsImageFilter () inline protected virtual
Definition at line 60 of file animaMCMScalarMapsImageFilter.h.
Member Function Documentation
CreateAnother()
template<class TPixelType > virtual::itk::LightObject::Pointer anima::MCMScalarMapsImageFilter< TPixelType >::CreateAnother (void) const
DynamicThreadedGenerateData()
template<class TPixelType > void anima::MCMScalarMapsImageFilter< TPixelType >::DynamicThreadedGenerateData (const InputRegionType & outputRegionForThread) protected
Definition at line 13 of file animaMCMScalarMapsImageFilter.hxx.
References anima::FreeWater, anima::BaseCompartment::GetApparentFractionalAnisotropy(), anima::BaseCompartment::GetApparentMeanDiffusivity(), anima::BaseCompartment::GetApparentParallelDiffusivity(), anima::BaseCompartment::GetApparentPerpendicularDiffusivity(), anima::BaseCompartment::GetCompartmentType(), anima::MCMImage< TPixel, VImageDimension >::GetDescriptionModel(), anima::IsotropicRestrictedWater, and anima::Stanisz.
Referenced by anima::MCMScalarMapsImageFilter< TPixelType >::isZero().
GetNameOfClass()
template<class TPixelType > virtual const char* anima::MCMScalarMapsImageFilter< TPixelType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
isZero()
template<class TPixelType > template<class T > bool anima::MCMScalarMapsImageFilter< TPixelType >::isZero (const itk::VariableLengthVector< T > & value) const inline protected
Definition at line 62 of file animaMCMScalarMapsImageFilter.h.
References anima::MCMScalarMapsImageFilter< TPixelType >::DynamicThreadedGenerateData().
New()
template<class TPixelType > static Pointer anima::MCMScalarMapsImageFilter< TPixelType >::New () static
Method for creation through the object factory.
SetIncludeIsotropicWeights()
template<class TPixelType > virtual void anima::MCMScalarMapsImageFilter< TPixelType >::SetIncludeIsotropicWeights (bool _arg) virtual
The documentation for this class was generated from the following files:
animaMCMScalarMapsImageFilter.h
animaMCMScalarMapsImageFilter.hxx