ANIMA: anima::BaseRootFindingAlgorithm Class Reference
anima::BaseRootFindingAlgorithm Class Reference abstract
#include <animaBaseRootFindingAlgorithm.h>
Public Types
using BaseCostFunctionPointer = BaseCostFunctionType::Pointer
using BaseCostFunctionType = itk::SingleValuedCostFunction
using ParametersType = BaseCostFunctionType::ParametersType
Public Member Functions
BaseRootFindingAlgorithm ()
double GetCostFunctionTolerance ()
double GetFunctionValueAtInitialLowerBound ()
double GetFunctionValueAtInitialUpperBound ()
double GetLowerBound ()
unsigned int GetMaximumNumberOfIterations ()
bool GetProvidedFunctionValueAtInitialLowerBound ()
bool GetProvidedFunctionValueAtInitialUpperBound ()
BaseCostFunctionType * GetRootFindingFunction ()
double GetRootRelativeTolerance ()
double GetUpperBound ()
virtual double Optimize ()=0
void SetCostFunctionTolerance (const double &val)
void SetFunctionValueAtInitialLowerBound (const double &val)
void SetFunctionValueAtInitialUpperBound (const double &val)
void SetLowerBound (const double &val)
void SetMaximumNumberOfIterations (const unsigned int &val)
void SetRootFindingFunction (BaseCostFunctionType *f)
void SetRootRelativeTolerance (const double &val)
void SetUpperBound (const double &val)
virtual ~BaseRootFindingAlgorithm ()
Detailed Description
Definition at line 47 of file animaBaseRootFindingAlgorithm.h.
Member Typedef Documentation
BaseCostFunctionPointer
using anima::BaseRootFindingAlgorithm::BaseCostFunctionPointer = BaseCostFunctionType::Pointer
Definition at line 51 of file animaBaseRootFindingAlgorithm.h.
BaseCostFunctionType
using anima::BaseRootFindingAlgorithm::BaseCostFunctionType = itk::SingleValuedCostFunction
Definition at line 50 of file animaBaseRootFindingAlgorithm.h.
ParametersType
using anima::BaseRootFindingAlgorithm::ParametersType = BaseCostFunctionType::ParametersType
Definition at line 52 of file animaBaseRootFindingAlgorithm.h.
Constructor & Destructor Documentation
BaseRootFindingAlgorithm()
anima::BaseRootFindingAlgorithm::BaseRootFindingAlgorithm () inline
Definition at line 76 of file animaBaseRootFindingAlgorithm.h.
~BaseRootFindingAlgorithm()
virtual anima::BaseRootFindingAlgorithm::~BaseRootFindingAlgorithm () inline virtual
Definition at line 87 of file animaBaseRootFindingAlgorithm.h.
Member Function Documentation
GetCostFunctionTolerance()
double anima::BaseRootFindingAlgorithm::GetCostFunctionTolerance () inline
Definition at line 71 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BisectionRootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), and anima::BrentRootFindingAlgorithm::Optimize().
GetFunctionValueAtInitialLowerBound()
double anima::BaseRootFindingAlgorithm::GetFunctionValueAtInitialLowerBound () inline
Definition at line 65 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BracketAndSolveRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), and anima::BrentRootFindingAlgorithm::Optimize().
GetFunctionValueAtInitialUpperBound()
double anima::BaseRootFindingAlgorithm::GetFunctionValueAtInitialUpperBound () inline
Definition at line 66 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BracketAndSolveRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), and anima::BrentRootFindingAlgorithm::Optimize().
GetLowerBound()
double anima::BaseRootFindingAlgorithm::GetLowerBound () inline
Definition at line 67 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BisectionRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), anima::BrentRootFindingAlgorithm::Optimize(), anima::BracketAndSolveRootFindingAlgorithm::Optimize(), and anima::BoostBisectionRootFindingAlgorithm::Optimize().
GetMaximumNumberOfIterations()
unsigned int anima::BaseRootFindingAlgorithm::GetMaximumNumberOfIterations () inline
Definition at line 69 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BisectionRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), anima::BrentRootFindingAlgorithm::Optimize(), anima::BracketAndSolveRootFindingAlgorithm::Optimize(), and anima::BoostBisectionRootFindingAlgorithm::Optimize().
GetProvidedFunctionValueAtInitialLowerBound()
bool anima::BaseRootFindingAlgorithm::GetProvidedFunctionValueAtInitialLowerBound () inline
Definition at line 63 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BracketAndSolveRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), and anima::BrentRootFindingAlgorithm::Optimize().
GetProvidedFunctionValueAtInitialUpperBound()
bool anima::BaseRootFindingAlgorithm::GetProvidedFunctionValueAtInitialUpperBound () inline
Definition at line 64 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BracketAndSolveRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), and anima::BrentRootFindingAlgorithm::Optimize().
GetRootFindingFunction()
BaseCostFunctionType* anima::BaseRootFindingAlgorithm::GetRootFindingFunction () inline
Definition at line 72 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BisectionRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), anima::BrentRootFindingAlgorithm::Optimize(), anima::BracketAndSolveRootFindingAlgorithm::Optimize(), and anima::BoostBisectionRootFindingAlgorithm::Optimize().
GetRootRelativeTolerance()
double anima::BaseRootFindingAlgorithm::GetRootRelativeTolerance () inline
Definition at line 70 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BisectionRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), anima::BrentRootFindingAlgorithm::Optimize(), anima::BracketAndSolveRootFindingAlgorithm::Optimize(), and anima::BoostBisectionRootFindingAlgorithm::Optimize().
GetUpperBound()
double anima::BaseRootFindingAlgorithm::GetUpperBound () inline
Definition at line 68 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BisectionRootFindingAlgorithm::Optimize(), anima::TOMS748RootFindingAlgorithm::Optimize(), anima::DekkerRootFindingAlgorithm::Optimize(), anima::BrentRootFindingAlgorithm::Optimize(), anima::BracketAndSolveRootFindingAlgorithm::Optimize(), and anima::BoostBisectionRootFindingAlgorithm::Optimize().
Optimize()
virtual double anima::BaseRootFindingAlgorithm::Optimize () pure virtual
Implemented in anima::BisectionRootFindingAlgorithm, anima::BoostBisectionRootFindingAlgorithm, anima::BracketAndSolveRootFindingAlgorithm, anima::BrentRootFindingAlgorithm, anima::DekkerRootFindingAlgorithm, and anima::TOMS748RootFindingAlgorithm.
SetCostFunctionTolerance()
void anima::BaseRootFindingAlgorithm::SetCostFunctionTolerance (const double & val) inline
Definition at line 55 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
SetFunctionValueAtInitialLowerBound()
void anima::BaseRootFindingAlgorithm::SetFunctionValueAtInitialLowerBound (const double & val)
Definition at line 17 of file animaBaseRootFindingAlgorithm.cxx.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
SetFunctionValueAtInitialUpperBound()
void anima::BaseRootFindingAlgorithm::SetFunctionValueAtInitialUpperBound (const double & val)
Definition at line 23 of file animaBaseRootFindingAlgorithm.cxx.
SetLowerBound()
void anima::BaseRootFindingAlgorithm::SetLowerBound (const double & val) inline
Definition at line 58 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
SetMaximumNumberOfIterations()
void anima::BaseRootFindingAlgorithm::SetMaximumNumberOfIterations (const unsigned int & val) inline
Definition at line 56 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
SetRootFindingFunction()
void anima::BaseRootFindingAlgorithm::SetRootFindingFunction (BaseCostFunctionType * f) inline
Definition at line 57 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
SetRootRelativeTolerance()
void anima::BaseRootFindingAlgorithm::SetRootRelativeTolerance (const double & val) inline
Definition at line 54 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
SetUpperBound()
void anima::BaseRootFindingAlgorithm::SetUpperBound (const double & val) inline
Definition at line 59 of file animaBaseRootFindingAlgorithm.h.
Referenced by anima::BoundedLevenbergMarquardtOptimizer::UpdateLambdaParameter().
The documentation for this class was generated from the following files:
animaBaseRootFindingAlgorithm.h
animaBaseRootFindingAlgorithm.cxx