ANIMA: anima::DWISimulatorFromDTIImageFilter< PixelScalarType > Class Template Reference
anima::DWISimulatorFromDTIImageFilter< PixelScalarType > Class Template Reference
#include <animaDWISimulatorFromDTIImageFilter.h>
Public Types
typedef itk::SmartPointer< const Self > ConstPointer
typedef itk::VectorImage< PixelScalarType, 3 > DTIImageType
typedef itk::Image< PixelScalarType, 4 > Image4DType
typedef InputImageType::Pointer InputImagePointer
typedef Superclass::InputImageRegionType InputImageRegionType
typedef TInputImage InputImageType
typedef InputImageType::PixelType InputPixelType
typedef TInputImage OutputB0ImageType
typedef OutputImageType::Pointer OutputImagePointer
typedef Superclass::OutputImageRegionType OutputImageRegionType
typedef TOutputImage OutputImageType
typedef itk::SmartPointer< Self > Pointer
typedef S0ImageType::Pointer S0ImagePointer
typedef itk::Image< PixelScalarType, 3 > S0ImageType
typedef DWISimulatorFromDTIImageFilter< PixelScalarType > Self
typedef itk::ImageToImageFilter< TInputImage, TOutputImage > Superclass
typedef itk::VectorImage< PixelScalarType, 3 > TInputImage
typedef itk::VectorImage< PixelScalarType, 3 > TOutputImage
Public Member Functions
void AddGradientDirection (unsigned int i, std::vector< double > &grad)
virtual ::itk::LightObject::Pointer CreateAnother (void) const
virtual const char * GetNameOfClass () const
Image4DType * GetOutputAs4DImage ()
virtual double GetS0Value ()
void SetBValuesList (std::vector< double > bValuesList)
virtual void SetS0Image (S0ImagePointer _arg)
virtual void SetS0Value (double _arg)
Static Public Member Functions
static Pointer New ()
Protected Member Functions
void BeforeThreadedGenerateData () ITK_OVERRIDE
DWISimulatorFromDTIImageFilter ()
void DynamicThreadedGenerateData (const OutputImageRegionType &outputRegionForThread) ITK_OVERRIDE
void GenerateOutputInformation () ITK_OVERRIDE
bool isZero (InputPixelType &vec)
virtual ~DWISimulatorFromDTIImageFilter ()
Detailed Description
template<class PixelScalarType>
class anima::DWISimulatorFromDTIImageFilter< PixelScalarType >
Definition at line 11 of file animaDWISimulatorFromDTIImageFilter.h.
Member Typedef Documentation
ConstPointer
template<class PixelScalarType> typedef itk::SmartPointer<const Self> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::ConstPointer
Definition at line 26 of file animaDWISimulatorFromDTIImageFilter.h.
DTIImageType
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType,3> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::DTIImageType
Definition at line 19 of file animaDWISimulatorFromDTIImageFilter.h.
Image4DType
template<class PixelScalarType> typedef itk::Image<PixelScalarType,4> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::Image4DType
Definition at line 20 of file animaDWISimulatorFromDTIImageFilter.h.
InputImagePointer
template<class PixelScalarType> typedef InputImageType::Pointer anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::InputImagePointer
Definition at line 38 of file animaDWISimulatorFromDTIImageFilter.h.
InputImageRegionType
template<class PixelScalarType> typedef Superclass::InputImageRegionType anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::InputImageRegionType
Superclass typedefs.
Definition at line 42 of file animaDWISimulatorFromDTIImageFilter.h.
InputImageType
template<class PixelScalarType> typedef TInputImage anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::InputImageType
Image typedef support
Definition at line 35 of file animaDWISimulatorFromDTIImageFilter.h.
InputPixelType
template<class PixelScalarType> typedef InputImageType::PixelType anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::InputPixelType
Definition at line 36 of file animaDWISimulatorFromDTIImageFilter.h.
OutputB0ImageType
template<class PixelScalarType> typedef TInputImage anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::OutputB0ImageType
Definition at line 18 of file animaDWISimulatorFromDTIImageFilter.h.
OutputImagePointer
template<class PixelScalarType> typedef OutputImageType::Pointer anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::OutputImagePointer
Definition at line 39 of file animaDWISimulatorFromDTIImageFilter.h.
OutputImageRegionType
template<class PixelScalarType> typedef Superclass::OutputImageRegionType anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::OutputImageRegionType
Definition at line 43 of file animaDWISimulatorFromDTIImageFilter.h.
OutputImageType
template<class PixelScalarType> typedef TOutputImage anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::OutputImageType
Definition at line 37 of file animaDWISimulatorFromDTIImageFilter.h.
Pointer
template<class PixelScalarType> typedef itk::SmartPointer<Self> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::Pointer
Definition at line 25 of file animaDWISimulatorFromDTIImageFilter.h.
S0ImagePointer
template<class PixelScalarType> typedef S0ImageType::Pointer anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::S0ImagePointer
Definition at line 22 of file animaDWISimulatorFromDTIImageFilter.h.
S0ImageType
template<class PixelScalarType> typedef itk::Image<PixelScalarType,3> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::S0ImageType
Definition at line 21 of file animaDWISimulatorFromDTIImageFilter.h.
Self
template<class PixelScalarType> typedef DWISimulatorFromDTIImageFilter<PixelScalarType> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::Self
Standard class typedefs.
Definition at line 16 of file animaDWISimulatorFromDTIImageFilter.h.
Superclass
template<class PixelScalarType> typedef itk::ImageToImageFilter< TInputImage, TOutputImage > anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::Superclass
Definition at line 24 of file animaDWISimulatorFromDTIImageFilter.h.
TInputImage
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType,3> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::TInputImage
Definition at line 17 of file animaDWISimulatorFromDTIImageFilter.h.
TOutputImage
template<class PixelScalarType> typedef itk::VectorImage<PixelScalarType,3> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::TOutputImage
Definition at line 23 of file animaDWISimulatorFromDTIImageFilter.h.
Constructor & Destructor Documentation
DWISimulatorFromDTIImageFilter()
template<class PixelScalarType> anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::DWISimulatorFromDTIImageFilter () inline protected
Definition at line 57 of file animaDWISimulatorFromDTIImageFilter.h.
~DWISimulatorFromDTIImageFilter()
template<class PixelScalarType> virtual anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::~DWISimulatorFromDTIImageFilter () inline protected virtual
Definition at line 67 of file animaDWISimulatorFromDTIImageFilter.h.
References anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::DynamicThreadedGenerateData(), anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GenerateOutputInformation(), and anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::isZero().
Member Function Documentation
AddGradientDirection()
template<class PixelScalarType > void anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::AddGradientDirection (unsigned int i, std::vector< double > & grad)
Definition at line 14 of file animaDWISimulatorFromDTIImageFilter.hxx.
References anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GenerateOutputInformation().
Referenced by anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::SetBValuesList().
BeforeThreadedGenerateData()
template<class PixelScalarType > void anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::BeforeThreadedGenerateData () protected
Definition at line 41 of file animaDWISimulatorFromDTIImageFilter.hxx.
References anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::DynamicThreadedGenerateData().
Referenced by anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GenerateOutputInformation(), and anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::~DWISimulatorFromDTIImageFilter().
CreateAnother()
template<class PixelScalarType> virtual::itk::LightObject::Pointer anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::CreateAnother (void) const
DynamicThreadedGenerateData()
template<class PixelScalarType > void anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::DynamicThreadedGenerateData (const OutputImageRegionType & outputRegionForThread) protected
Definition at line 65 of file animaDWISimulatorFromDTIImageFilter.hxx.
References anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::isZero().
Referenced by anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::BeforeThreadedGenerateData(), and anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::~DWISimulatorFromDTIImageFilter().
GenerateOutputInformation()
template<class PixelScalarType > void anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GenerateOutputInformation () protected
Definition at line 27 of file animaDWISimulatorFromDTIImageFilter.hxx.
References anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::BeforeThreadedGenerateData().
Referenced by anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::AddGradientDirection(), and anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::~DWISimulatorFromDTIImageFilter().
GetNameOfClass()
template<class PixelScalarType> virtual const char* anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GetNameOfClass () const virtual
Run-time type information (and related methods)
GetOutputAs4DImage()
template<class PixelScalarType > DWISimulatorFromDTIImageFilter< PixelScalarType >::Image4DType * anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GetOutputAs4DImage ()
Definition at line 144 of file animaDWISimulatorFromDTIImageFilter.hxx.
Referenced by anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::isZero(), and anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::SetBValuesList().
GetS0Value()
template<class PixelScalarType> virtual double anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GetS0Value () virtual
isZero()
template<class PixelScalarType > bool anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::isZero (InputPixelType & vec) protected
Definition at line 128 of file animaDWISimulatorFromDTIImageFilter.hxx.
References anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GetOutputAs4DImage().
Referenced by anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::DynamicThreadedGenerateData(), and anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::~DWISimulatorFromDTIImageFilter().
New()
template<class PixelScalarType> static Pointer anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::New () static
Method for creation through the object factory.
SetBValuesList()
template<class PixelScalarType> void anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::SetBValuesList (std::vector< double > bValuesList) inline
Definition at line 45 of file animaDWISimulatorFromDTIImageFilter.h.
References anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::AddGradientDirection(), and anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::GetOutputAs4DImage().
SetS0Image()
template<class PixelScalarType> virtual void anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::SetS0Image (S0ImagePointer _arg) virtual
SetS0Value()
template<class PixelScalarType> virtual void anima::DWISimulatorFromDTIImageFilter< PixelScalarType >::SetS0Value (double _arg) virtual
The documentation for this class was generated from the following files:
animaDWISimulatorFromDTIImageFilter.h
animaDWISimulatorFromDTIImageFilter.hxx