ANIMA: anima::B1GammaDistributionIntegrand Class Reference
anima::B1GammaDistributionIntegrand Class Reference
Integrand to compute the internal integral per distribution in B1GammaMixtureT2RelaxometryCostFunction.
#include <animaB1GammaDistributionIntegrand.h>
Public Types
using EPGVectorsMapType = std::map< double, anima::EPGSignalSimulator::RealVectorType >
Public Member Functions
B1GammaDistributionIntegrand (anima::EPGSignalSimulator &sigSim, EPGVectorsMapType &val)
virtual double operator() (double const t)
void SetEchoNumber (unsigned int val)
void SetFlipAngle (double val)
void SetGammaMean (double val)
void SetGammaVariance (double val)
void SetT1Value (double val)
Protected Attributes
unsigned int m_EchoNumber
anima::EPGSignalSimulator & m_EPGSimulator
EPG signal simulator reference: instantiated outside.
EPGVectorsMapType & m_EPGVectors
Since boost Gauss Legendre integration works on object copies, we need to keep a reference to EPG vectors, held externally.
double m_FlipAngle
double m_GammaMean
double m_GammaVariance
double m_T1Value
Detailed Description
Integrand to compute the internal integral per distribution in B1GammaMixtureT2RelaxometryCostFunction.
Definition at line 16 of file animaB1GammaDistributionIntegrand.h.
Member Typedef Documentation
EPGVectorsMapType
using anima::B1GammaDistributionIntegrand::EPGVectorsMapType = std::map <double, anima::EPGSignalSimulator::RealVectorType>
Definition at line 19 of file animaB1GammaDistributionIntegrand.h.
Constructor & Destructor Documentation
B1GammaDistributionIntegrand()
anima::B1GammaDistributionIntegrand::B1GammaDistributionIntegrand (anima::EPGSignalSimulator & sigSim, EPGVectorsMapType & val) inline
Definition at line 20 of file animaB1GammaDistributionIntegrand.h.
Member Function Documentation
operator()()
double anima::B1GammaDistributionIntegrand::operator() (double const t) virtual
Reimplemented in anima::B1GammaDerivativeDistributionIntegrand.
Definition at line 9 of file animaB1GammaDistributionIntegrand.cxx.
References anima::EPGSignalSimulator::GetValue(), m_EchoNumber, m_EPGSimulator, m_EPGVectors, m_FlipAngle, m_GammaMean, m_GammaVariance, and m_T1Value.
SetEchoNumber()
void anima::B1GammaDistributionIntegrand::SetEchoNumber (unsigned int val) inline
Definition at line 25 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative(), and anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS().
SetFlipAngle()
void anima::B1GammaDistributionIntegrand::SetFlipAngle (double val) inline
Definition at line 24 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative(), and anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS().
SetGammaMean()
void anima::B1GammaDistributionIntegrand::SetGammaMean (double val) inline
Definition at line 27 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative(), and anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS().
SetGammaVariance()
void anima::B1GammaDistributionIntegrand::SetGammaVariance (double val) inline
Definition at line 28 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative(), and anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS().
SetT1Value()
void anima::B1GammaDistributionIntegrand::SetT1Value (double val) inline
Definition at line 23 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForDerivative(), and anima::B1GammaMixtureT2RelaxometryCostFunction::PrepareDataForLLS().
Member Data Documentation
m_EchoNumber
unsigned int anima::B1GammaDistributionIntegrand::m_EchoNumber protected
Definition at line 38 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaDerivativeDistributionIntegrand::operator()(), and operator()().
m_EPGSimulator
anima::EPGSignalSimulator& anima::B1GammaDistributionIntegrand::m_EPGSimulator protected
EPG signal simulator reference: instantiated outside.
Definition at line 34 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaDerivativeDistributionIntegrand::operator()(), and operator()().
m_EPGVectors
EPGVectorsMapType& anima::B1GammaDistributionIntegrand::m_EPGVectors protected
Since boost Gauss Legendre integration works on object copies, we need to keep a reference to EPG vectors, held externally.
Definition at line 41 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaDerivativeDistributionIntegrand::operator()(), and operator()().
m_FlipAngle
double anima::B1GammaDistributionIntegrand::m_FlipAngle protected
Definition at line 37 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaDerivativeDistributionIntegrand::operator()(), and operator()().
m_GammaMean
double anima::B1GammaDistributionIntegrand::m_GammaMean protected
Definition at line 43 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaDerivativeDistributionIntegrand::operator()(), and operator()().
m_GammaVariance
double anima::B1GammaDistributionIntegrand::m_GammaVariance protected
Definition at line 43 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaDerivativeDistributionIntegrand::operator()(), and operator()().
m_T1Value
double anima::B1GammaDistributionIntegrand::m_T1Value protected
Definition at line 36 of file animaB1GammaDistributionIntegrand.h.
Referenced by anima::B1GammaDerivativeDistributionIntegrand::operator()(), and operator()().
The documentation for this class was generated from the following files:
animaB1GammaDistributionIntegrand.h
animaB1GammaDistributionIntegrand.cxx